In [1]:
import pandas as pd

### Question 1

Create a **Pandas Series** from the list `[10, 20, 30, 40, 50]`.  
Print the Series, its **index**, and **data type**.  

Then, create a **DataFrame** with columns `"Name"`, `"Age"`, and `"City"` containing at least **4 rows of data**.

In [3]:
lst = [10, 20, 30, 40, 50]
lst_sr = pd.Series(lst)
lst_sr

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [5]:
idx = lst_sr.index
print(idx)
print(list(idx))

RangeIndex(start=0, stop=5, step=1)
[0, 1, 2, 3, 4]

In [6]:
lst_sr.dtype

dtype('int64')

In [13]:
df = pd.DataFrame({
    "Name": ["Mashrur", "Safir", "Shabab", "Ahmed"],
    "Age": [21, 22, 23, 24],
    "City": ["Dhaka", "Khulna", "Rajshahi", "Sylhet"],
},index=[1, 2, 3, 4])
df

      Name  Age      City
1  Mashrur   21     Dhaka
2    Safir   22    Khulna
3   Shabab   23  Rajshahi
4    Ahmed   24    Sylhet

### Question 2

Using any **DataFrame**, write code to:

- Print the **number of rows and columns**.  
- Display the **column data types** using `.dtypes`.  
- Show the **summary statistics** using `.describe()`.

In [17]:
print(f"Number of rows: {len(list(df.index))}")

Number of rows: 4

In [18]:
print(f"Number of columns: {len(list(df.columns))}")

Number of columns: 3

In [23]:
df.dtypes

Name    object
Age      int64
City    object
dtype: object

In [24]:
df.describe()

             Age
count   4.000000
mean   22.500000
std     1.290994
min    21.000000
25%    21.750000
50%    22.500000
75%    23.250000
max    24.000000

### Question 3

Create a **DataFrame** using the dictionary below:

```python
data = {
    'Product': ['Pen', 'Book', 'Eraser', 'Pencil'],
    'Price': [10, 50, 5, 7],
    'Quantity': [100, 60, 200, 150]
}
```

Print the `.columns` and `.index`.
Access a single column and one full row from the DataFrame.

In [26]:
data = {
    'Product': ['Pen', 'Book', 'Eraser', 'Pencil'],
    'Price': [10, 50, 5, 7],
    'Quantity': [100, 60, 200, 150]
}

df = pd.DataFrame(data)

In [27]:
df

  Product  Price  Quantity
0     Pen     10       100
1    Book     50        60
2  Eraser      5       200
3  Pencil      7       150

In [28]:
df.columns

Index(['Product', 'Price', 'Quantity'], dtype='object')

In [29]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [30]:
df["Product"]

0       Pen
1      Book
2    Eraser
3    Pencil
Name: Product, dtype: object

In [33]:
df[0:1]

  Product  Price  Quantity
0     Pen     10       100

### Question 4

Using **`.loc[]`** and **`.iloc[]`**, do the following:

- Show the **first row**.  
- Show the **second column**.  
- Display a **2×2 block** from the **middle** of your DataFrame.

In [34]:
df.loc[0]

Product     Pen
Price        10
Quantity    100
Name: 0, dtype: object

In [36]:
df.iloc[:,1]

0    10
1    50
2     5
3     7
Name: Price, dtype: int64

In [37]:
df.iloc[1:3, 1:3]

   Price  Quantity
1     50        60
2      5       200

### Question 5

Create a **4×3 DataFrame** containing **student names** and **marks**.  

- Drop one **column** using `.drop()`.  
- Drop one **row** by **index**.

In [38]:
df = pd.DataFrame({
    "Names": ["Mashrur", "Safir", "Shabab", "Ahmed"],
    "Marks": [1, 2, 3, 4],
})

In [41]:
df

     Names  Marks
0  Mashrur      1
1    Safir      2
2   Shabab      3
3    Ahmed      4

In [ ]:
df.drop("Names", axis=1, inplace=True)

In [47]:
df

   Marks
0      1
1      2
2      3
3      4

In [48]:
df.drop(0, inplace=True)
df

   Marks
1      2
2      3
3      4

### Question 6

Create a **DataFrame** of employees with columns `"Name"`, `"Department"`, and `"Salary"`.  

- **Sort** the DataFrame by `"Salary"` in **ascending** order.  
- Then sort it by `"Name"` in **descending** order.

In [59]:
df = pd.DataFrame({
    "Name": ["Mashrur", "Safir", "Shabab", "Ahmed"],
    "Department": ["CS", "EEE", "Mechatronics", "Robotics"],
    "Salary": [1, 2, 1, 2],
})

df

      Name    Department  Salary
0  Mashrur            CS       1
1    Safir           EEE       2
2   Shabab  Mechatronics       1
3    Ahmed      Robotics       2

In [62]:
df.sort_values(["Salary", "Name"], ascending=[1, 0], inplace=True)
df

      Name    Department  Salary
2   Shabab  Mechatronics       1
0  Mashrur            CS       1
1    Safir           EEE       2
3    Ahmed      Robotics       2

### Question 7

Create a **DataFrame** of **8 students** with columns `"Name"` and `"Score"`.  

- **Filter** and print students with **Score > 60**.  
- **Filter** and print students with **Score < 40**.

In [64]:
df = pd.DataFrame({
    "Name": ["Mashrur", "Safir", "Shabab", "Ahmed", "Alice", "Bob", "Charlie", "Carol"],
    "Score": [10, 20, 30, 40, 50, 60, 70, 80],
})

df

      Name  Score
0  Mashrur     10
1    Safir     20
2   Shabab     30
3    Ahmed     40
4    Alice     50
5      Bob     60
6  Charlie     70
7    Carol     80

In [69]:
df[df["Score"] > 60]

      Name  Score
6  Charlie     70
7    Carol     80

In [71]:
df[df["Score"] < 40]

      Name  Score
0  Mashrur     10
1    Safir     20
2   Shabab     30