**shabab.ahmed2000sa@gmail.com**

# 0) Starter Code (Run First)

In [2]:
# You must run this code and use that data set for all the questions
import numpy as np
import pandas as pd

np.random.seed(42)

ids = np.arange(1, 11)
ages = np.random.randint(18, 60, 10)
salaries = np.random.randint(30000, 90000, 10)
departments = np.array(["HR", "IT", "Finance", "IT", "HR", "Sales", "Finance", "IT", "Sales", "HR"])

DF = pd.DataFrame({
"id": ids,
"age": ages,
"salary": salaries,
"dept": departments
})

DF.to_csv("employees.csv", index=False)
print("Sample Data Created and Saved as employees.csv")

Sample Data Created and Saved as employees.csv

# 1) NumPy — 5 Questions

## Q1. Create NumPy arrays from the ages and salaries data generated above. Print both arrays and display their **dtype**, **ndim**, **shape**, and **size**.

In [69]:
ages_np = np.array(ages)
print(f"ages: {ages_np}")
print(f"dtype: {ages_np.dtype}")
print(f"ndim: {ages_np.ndim}")
print(f"shape: {ages_np.shape}")
print(f"size: {ages_np.size}")

ages: [56 46 32 25 38 56 36 40 28 28]
dtype: int64
ndim: 1
shape: (10,)
size: 10

In [70]:
salaries_np = np.array(salaries)
print(f"salaries: {salaries_np}")
print(f"dtype: {salaries_np.dtype}")
print(f"ndim: {salaries_np.ndim}")
print(f"shape: {salaries_np.shape}")
print(f"size: {salaries_np.size}")

salaries: [77191 74131 46023 71090 31685 30769 89735 86101 32433 35311]
dtype: int64
ndim: 1
shape: (10,)
size: 10

## Q2. Using the **salaries** array, find and print the highest and lowest salary values. Also, calculate and print the average salary and age using NumPy functions.

In [76]:
highest_salary_index = np.argmax(salaries_np)
print(f"Highest Salary: {salaries_np[highest_salary_index]}")

Highest Salary: 89735

In [77]:
lowest_salary_index = np.argmin(salaries_np)
print(f"Lowest Salary: {salaries_np[lowest_salary_index]}")

Lowest Salary: 30769

In [78]:
avg_salary = np.average(salaries_np)
print(f"Average Salary: {avg_salary}")

Average Salary: 57446.9

In [79]:
avg_age = np.average(ages_np)
print(f"Average age: {avg_age}")

Average age: 38.5

## Q3. From the **ages** array, filter and print all ages greater than 30 using a boolean condition. Then count and print how many employees are older than 30.

In [84]:
greater_than_30 = ages_np > 30
greater_than_30

array([ True,  True,  True, False,  True,  True,  True,  True, False,
       False])

In [85]:
ages_np[ages_np>30]

array([56, 46, 32, 38, 56, 36, 40])

In [87]:
print(len(ages_np[ages_np>30]))

7

In [82]:
print(np.count_nonzero(greater_than_30))

7

## Q4. Create a new NumPy array that increases every employee’s age by 5 years (without modifying the original array). Print the new updated ages array.

In [89]:
# old ages array = [56 46 32 25 38 56 36 40 28 28]

In [88]:
new_ages_np = ages_np + 5
print(new_ages_np)

[61 51 37 30 43 61 41 45 33 33]

In [90]:
print(f"Old ages array: {ages_np}")
print(f"new ages array: {new_ages_np}")

Old ages array: [56 46 32 25 38 56 36 40 28 28]
new ages array: [61 51 37 30 43 61 41 45 33 33]

## Q5. Using NumPy, calculate the total salary expense (sum of all salaries) and the difference between the maximum and minimum salary. Print both results.

In [91]:
totalSalary = np.sum(salaries_np)
print(f"Total salary expense: {totalSalary}")

Total salary expense: 574469

In [93]:
maxSalary = np.max(salaries_np)
print(f"Maximum Salary: {maxSalary}")

Maximum Salary: 89735

In [94]:
minSalary = np.min(salaries_np)
print(f"Minimum Salary: {minSalary}")

Minimum Salary: 30769

In [95]:
diff = maxSalary - minSalary
print(f"Difference between maximum and minimum salary: {diff}")

Difference between maximum and minimum salary: 58966

# 2) Pandas — 5 Questions

## Q6. Load the employees.csv file into a Pandas DataFrame. Display the first 5 rows, and check basic info using `info()` and summary statistics using `describe()`.

In [3]:
df = pd.read_csv("employees.csv")
df

   id  age  salary     dept
0   1   56   77191       HR
1   2   46   74131       IT
2   3   32   46023  Finance
3   4   25   71090       IT
4   5   38   31685       HR
5   6   56   30769    Sales
6   7   36   89735  Finance
7   8   40   86101       IT
8   9   28   32433    Sales
9  10   28   35311       HR

In [4]:
df.head()

   id  age  salary     dept
0   1   56   77191       HR
1   2   46   74131       IT
2   3   32   46023  Finance
3   4   25   71090       IT
4   5   38   31685       HR

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      10 non-null     int64
 1   age     10 non-null     int64
 2   salary  10 non-null     int64
 3   dept    10 non-null     object
dtypes: int64(3), object(1)
memory usage: 452.0+ bytes

In [6]:
df.describe()

             id       age        salary
count  10.00000  10.00000     10.000000
mean    5.50000  38.50000  57446.900000
std     3.02765  11.16791  24357.262884
min     1.00000  25.00000  30769.000000
25%     3.25000  29.00000  33152.500000
50%     5.50000  37.00000  58556.500000
75%     7.75000  44.50000  76426.000000
max    10.00000  56.00000  89735.000000

## Q7. Display only the **id**, **age**, and **salary** columns. Then show the last 3 rows using `tail()`.

In [18]:
x = df[["id", "age", "salary"]]
x

   id  age  salary
0   1   56   77191
1   2   46   74131
2   3   32   46023
3   4   25   71090
4   5   38   31685
5   6   56   30769
6   7   36   89735
7   8   40   86101
8   9   28   32433
9  10   28   35311

In [19]:
x.tail(3)

   id  age  salary
7   8   40   86101
8   9   28   32433
9  10   28   35311

## Q8. Filter the DataFrame to show only employees who work in the **IT** department. Print the result and show the total number of IT employees.

In [20]:
df[df["dept"] == "IT"]

   id  age  salary dept
1   2   46   74131   IT
3   4   25   71090   IT
7   8   40   86101   IT

In [23]:
total = (df["dept"] == "IT").sum()
print(total)

3

## Q9. Sort the DataFrame by **salary** in descending order and display the top 3 highest-paid employees along with their **department** and **age**.

In [24]:
df.sort_values("salary", ascending=False, inplace=True)
df

   id  age  salary     dept
6   7   36   89735  Finance
7   8   40   86101       IT
0   1   56   77191       HR
1   2   46   74131       IT
3   4   25   71090       IT
2   3   32   46023  Finance
9  10   28   35311       HR
8   9   28   32433    Sales
4   5   38   31685       HR
5   6   56   30769    Sales

In [45]:
df.head(3)

   id  age  salary     dept
6   7   36   89735  Finance
7   8   40   86101       IT
0   1   56   77191       HR

In [49]:
df[["dept", "age"]].head(3)

      dept  age
6  Finance   36
7       IT   40
0       HR   56

## Q10. Replace all salary values greater than **80000** with **80000** using `loc`. Then calculate and print the new average salary of all employees after replacement.

In [59]:
df.loc[df["salary"] > 80000, "salary"] = 80000

In [60]:
df

   id  age  salary     dept
6   7   36   80000  Finance
7   8   40   80000       IT
0   1   56   77191       HR
1   2   46   74131       IT
3   4   25   71090       IT
2   3   32   46023  Finance
9  10   28   35311       HR
8   9   28   32433    Sales
4   5   38   31685       HR
5   6   56   30769    Sales

In [61]:
print(df["salary"].mean())

55863.3