# Pandas

In [1]:
import pandas as pd
import numpy as np

## Different file loading

### csv file

In [11]:
df = pd.read_csv("student_data.csv")
print(df, type(df))

   StudentID          FullName  Data Structure Marks  Algorithm Marks  \
0     PH1001       Alif Rahman                  85.0             85.0
1     PH1002     Fatima Akhter                  92.0             92.0
2     PH1003     Imran Hossain                  88.0             88.0
3     PH1004  Jannatul Ferdous                  78.0             78.0
4     PH1005       Kamal Uddin                   NaN              NaN
5     PH1006       Laila Begum                  75.0             75.0
6     PH1007    Mahmudul Hasan                  80.0             80.0
7     PH1008       Nadia Islam                  81.0             81.0
8     PH1009        Omar Faruq                  72.0             72.0
9     PH1010      Priya Sharma                  89.0             89.0
10    PH1011      Rahim Sheikh                   NaN              NaN
11    PH1012   Sadia Chowdhury                  85.0             85.0
12    PH1013      Tanvir Ahmed                  75.0             75.0
13    PH1014        Urmi Akter                   NaN              NaN
14    PH1015      Wahiduzzaman                  86.0             86.0
15    PH1016      Ziaur Rahman                  94.0             94.0
16    PH1017       Afsana Mimi                  90.0             90.0
17    PH1018       Babul Ahmed                  88.0             88.0
18    PH1019      Faria Rahman                   NaN              NaN
19    PH1020        Nasir Khan                  86.0             86.0
20       NaN               NaN                   NaN              NaN

    Python Marks CompletionStatus EnrollmentDate Instructor    Location
0           88.0        Completed     2024-01-15  Mr. Karim       Dhaka
1            NaN      In Progress     2024-01-20  Ms. Salma  Chattogram
2           85.0        Completed     2024-02-10  Mr. Karim       Dhaka
3           82.0        Completed     2024-02-12  Ms. Salma      Sylhet
4           95.0      In Progress     2024-03-05  Mr. Karim  Chattogram
5           78.0        Completed     2024-03-08  Ms. Salma    Rajshahi
6            NaN      In Progress     2024-04-01  Mr. Karim       Dhaka
7           85.0        Completed     2024-04-22  Ms. Salma  Chattogram
8           76.0        Completed     2024-05-16  Mr. David       Dhaka
9           88.0        Completed     2024-05-20  Ms. Salma      Sylhet
10          91.0      In Progress     2024-06-11  Mr. Karim      Khulna
11          87.0        Completed     2024-06-14  Ms. Salma  Chattogram
12          79.0        Completed     2024-07-02  Mr. David       Dhaka
13           NaN      Not Started     2024-07-09  Ms. Salma    Rajshahi
14          84.0        Completed     2024-08-18  Mr. Karim       Dhaka
15           NaN      In Progress     2024-08-21  Ms. Salma  Chattogram
16          93.0        Completed     2025-09-01  Mr. Karim       Dhaka
17          85.0        Completed     2025-09-05  Ms. Salma      Sylhet
18           NaN      Not Started     2025-09-15  Mr. David  Chattogram
19          89.0        Completed     2025-10-02  Ms. Salma       Dhaka
20           NaN              NaN            NaN        NaN         NaN   <class 'pandas.core.frame.DataFrame'>

In [32]:
student_id = df["StudentID"]
print(student_id, type(student_id))

0     PH1001
1     PH1002
2     PH1003
3     PH1004
4     PH1005
5     PH1006
6     PH1007
7     PH1008
8     PH1009
9     PH1010
10    PH1011
11    PH1012
12    PH1013
13    PH1014
14    PH1015
15    PH1016
16    PH1017
17    PH1018
18    PH1019
19    PH1020
Name: StudentID, dtype: object <class 'pandas.core.series.Series'>

:

:

### excel file

In [21]:
df_xlsx = pd.read_excel('student_marks.xlsx')
print(df_xlsx, type(df_xlsx))

   StudentID          FullName  Data Structure Marks  Algorithm Marks  \
0     PH1001       Alif Rahman                  85.0             85.0
1     PH1002     Fatima Akhter                  92.0             92.0
2     PH1003     Imran Hossain                  88.0             88.0
3     PH1004  Jannatul Ferdous                  78.0             78.0
4     PH1005       Kamal Uddin                   NaN              NaN
5     PH1006       Laila Begum                  75.0             75.0
6     PH1007    Mahmudul Hasan                  80.0             80.0
7     PH1008       Nadia Islam                  81.0             81.0
8     PH1009        Omar Faruq                  72.0             72.0
9     PH1010      Priya Sharma                  89.0             89.0
10    PH1011      Rahim Sheikh                   NaN              NaN
11    PH1012   Sadia Chowdhury                  85.0             85.0
12    PH1013      Tanvir Ahmed                  75.0             75.0
13    PH1014        Urmi Akter                   NaN              NaN
14    PH1015      Wahiduzzaman                  86.0             86.0
15    PH1016      Ziaur Rahman                  94.0             94.0
16    PH1017       Afsana Mimi                  90.0             90.0
17    PH1018       Babul Ahmed                  88.0             88.0
18    PH1019      Faria Rahman                   NaN              NaN
19    PH1020        Nasir Khan                  86.0             86.0

    Python Marks CompletionStatus EnrollmentDate Instructor    Location
0           88.0        Completed     2024-01-15  Mr. Karim       Dhaka
1            NaN      In Progress     2024-01-20  Ms. Salma  Chattogram
2           85.0        Completed     2024-02-10  Mr. Karim       Dhaka
3           82.0        Completed     2024-02-12  Ms. Salma      Sylhet
4           95.0      In Progress     2024-03-05  Mr. Karim  Chattogram
5           78.0        Completed     2024-03-08  Ms. Salma    Rajshahi
6            NaN      In Progress     2024-04-01  Mr. Karim       Dhaka
7           85.0        Completed     2024-04-22  Ms. Salma  Chattogram
8           76.0        Completed     2024-05-16  Mr. David       Dhaka
9           88.0        Completed     2024-05-20  Ms. Salma      Sylhet
10          91.0      In Progress     2024-06-11  Mr. Karim      Khulna
11          87.0        Completed     2024-06-14  Ms. Salma  Chattogram
12          79.0        Completed     2024-07-02  Mr. David       Dhaka
13           NaN      Not Started     2024-07-09  Ms. Salma    Rajshahi
14          84.0        Completed     2024-08-18  Mr. Karim       Dhaka
15           NaN      In Progress     2024-08-21  Ms. Salma  Chattogram
16          93.0        Completed     2025-09-01  Mr. Karim       Dhaka
17          85.0        Completed     2025-09-05  Ms. Salma      Sylhet
18           NaN      Not Started     2025-09-15  Mr. David  Chattogram
19          89.0        Completed     2025-10-02  Ms. Salma       Dhaka   <class 'pandas.core.frame.DataFrame'>

:

In [34]:
import pyarrow

:

:

### parquet file

In [35]:
df_parquet = pd.read_parquet('student_marks.parquet')
print(df_parquet, type(df_parquet))

   StudentID          FullName  Data Structure Marks  Algorithm Marks  \
0     PH1001       Alif Rahman                  85.0             85.0
1     PH1002     Fatima Akhter                  92.0             92.0
2     PH1003     Imran Hossain                  88.0             88.0
3     PH1004  Jannatul Ferdous                  78.0             78.0
4     PH1005       Kamal Uddin                   NaN              NaN
5     PH1006       Laila Begum                  75.0             75.0
6     PH1007    Mahmudul Hasan                  80.0             80.0
7     PH1008       Nadia Islam                  81.0             81.0
8     PH1009        Omar Faruq                  72.0             72.0
9     PH1010      Priya Sharma                  89.0             89.0
10    PH1011      Rahim Sheikh                   NaN              NaN
11    PH1012   Sadia Chowdhury                  85.0             85.0
12    PH1013      Tanvir Ahmed                  75.0             75.0
13    PH1014        Urmi Akter                   NaN              NaN
14    PH1015      Wahiduzzaman                  86.0             86.0
15    PH1016      Ziaur Rahman                  94.0             94.0
16    PH1017       Afsana Mimi                  90.0             90.0
17    PH1018       Babul Ahmed                  88.0             88.0
18    PH1019      Faria Rahman                   NaN              NaN
19    PH1020        Nasir Khan                  86.0             86.0

    Python Marks CompletionStatus EnrollmentDate Instructor    Location
0           88.0        Completed     2024-01-15  Mr. Karim       Dhaka
1            NaN      In Progress     2024-01-20  Ms. Salma  Chattogram
2           85.0        Completed     2024-02-10  Mr. Karim       Dhaka
3           82.0        Completed     2024-02-12  Ms. Salma      Sylhet
4           95.0      In Progress     2024-03-05  Mr. Karim  Chattogram
5           78.0        Completed     2024-03-08  Ms. Salma    Rajshahi
6            NaN      In Progress     2024-04-01  Mr. Karim       Dhaka
7           85.0        Completed     2024-04-22  Ms. Salma  Chattogram
8           76.0        Completed     2024-05-16  Mr. David       Dhaka
9           88.0        Completed     2024-05-20  Ms. Salma      Sylhet
10          91.0      In Progress     2024-06-11  Mr. Karim      Khulna
11          87.0        Completed     2024-06-14  Ms. Salma  Chattogram
12          79.0        Completed     2024-07-02  Mr. David       Dhaka
13           NaN      Not Started     2024-07-09  Ms. Salma    Rajshahi
14          84.0        Completed     2024-08-18  Mr. Karim       Dhaka
15           NaN      In Progress     2024-08-21  Ms. Salma  Chattogram
16          93.0        Completed     2025-09-01  Mr. Karim       Dhaka
17          85.0        Completed     2025-09-05  Ms. Salma      Sylhet
18           NaN      Not Started     2025-09-15  Mr. David  Chattogram
19          89.0        Completed     2025-10-02  Ms. Salma       Dhaka   <class 'pandas.core.frame.DataFrame'>

:

:

### json file

In [36]:
df_json = pd.read_json('student_marks.json')
print(df_json, type(df_json))

  StudentID          FullName  Data Structure Marks  Algorithm Marks  \
0    PH1001       Alif Rahman                    85               85
1    PH1002     Fatima Akhter                    92               92
2    PH1004  Jannatul Ferdous                    78               78

   Python Marks
0            88
1            90
2            82   <class 'pandas.core.frame.DataFrame'>

:

:

## df

In [37]:
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

:

:

### head()
shows the first 5 rows of the data frame if no parameter is passed
so by default, the parameter is 5

In [38]:
df.head()

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram

:

:

In [39]:
df.head(9)

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka

:

:

### tail()
by default shows the last 5 rows if no parameter is passed

In [40]:
df.tail()

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

:

:

In [41]:
df.tail(2)

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

:

:

### columns
attribute of the df class

In [42]:
df.columns

Index(['StudentID', 'FullName', 'Data Structure Marks', 'Algorithm Marks',
       'Python Marks', 'CompletionStatus', 'EnrollmentDate', 'Instructor',
       'Location'],
      dtype='object')

:

:

In [43]:
col = list(df.columns)
print(col, type(col))

['StudentID', 'FullName', 'Data Structure Marks', 'Algorithm Marks', 'Python Marks', 'CompletionStatus', 'EnrollmentDate', 'Instructor', 'Location'] <class 'list'>

:

:

In [46]:
col2 = np.array(df.columns)
print(col2, col2.dtype)

['StudentID' 'FullName' 'Data Structure Marks' 'Algorithm Marks'
 'Python Marks' 'CompletionStatus' 'EnrollmentDate' 'Instructor'
 'Location'] object

:

:

### index
this is the attribute of the df class which shows the range of the starting to ending_index+1 of the data frame

In [47]:
df.index

RangeIndex(start=0, stop=20, step=1)

:

:

In [48]:
idx = np.array(df.index)
print(idx, idx.dtype)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] int64

:

:

### info()
shows info regarding df

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   StudentID             20 non-null     object
 1   FullName              20 non-null     object
 2   Data Structure Marks  16 non-null     float64
 3   Algorithm Marks       16 non-null     float64
 4   Python Marks          15 non-null     float64
 5   CompletionStatus      20 non-null     object
 6   EnrollmentDate        20 non-null     object
 7   Instructor            20 non-null     object
 8   Location              20 non-null     object
dtypes: float64(3), object(6)
memory usage: 1.5+ KB

:

:

### sample()
by default shows only 1 sample data randomly (if no parameter is passed)

In [50]:
df.sample()

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram

:

:

In [51]:
df.sample(10)

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram

:

:

### statistical values

#### describe()

In [52]:
df.describe()

       Data Structure Marks  Algorithm Marks  Python Marks
count             16.000000        16.000000     15.000000
mean              84.000000        84.000000     85.666667
std                6.501282         6.501282      5.394000
min               72.000000        72.000000     76.000000
25%               79.500000        79.500000     83.000000
50%               85.500000        85.500000     85.000000
75%               88.250000        88.250000     88.500000
max               94.000000        94.000000     95.000000

:

:

## Transforming to series from inbuilt data

### list

In [53]:
l = [10, 20, 30]
l_sr = pd.Series(l, index=["x", "y", "z"])
print(type(l_sr))
l_sr

<class 'pandas.core.series.Series'>

x    10
y    20
z    30
dtype: int64

:

:

#### accessing by key

In [54]:
print(l_sr["x"])

10

:

:

#### accessing by index

In [55]:
print(l[0])

10

:

:

#### accessing by multipe keys

In [56]:
print(l_sr[["x", "z"]])

x    10
z    30
dtype: int64

:

:

#### accessing via label - loc() and index - iloc()

In [57]:
# loc() only works with the value that is assiged to the index
print(l_sr.loc["x"])

10

:

:

In [58]:
print(l_sr.loc[["x", "y"]])

x    10
y    20
dtype: int64

:

:

In [59]:
# iloc() only works with integer values
print(l_sr.iloc[0])

10

:

:

#### series slicing

##### using values assigned in index

In [60]:
print(l_sr["x":"y"])    # loc()

x    10
y    20
dtype: int64

:

:

In [61]:
l_sr.loc["x":"y"]

x    10
y    20
dtype: int64

:

:

##### using index values

In [62]:
l_sr[0:2]    # iloc()

x    10
y    20
dtype: int64

:

:

In [65]:
l_sr.iloc[0:2]

x    10
y    20
dtype: int64

:

##### get()

In [63]:
print(l_sr.get("x", 0))

10

:

:

In [64]:
# 0 is the default value that will be displayed if the index/key is not found
print(l_sr.get("a", 0))

0

:

:

### dictionary

In [66]:
d = {"a":10, "b":20, "c":30}
d_sr = pd.Series(d)
print(type(d_sr))
d_sr

<class 'pandas.core.series.Series'>

a    10
b    20
c    30
dtype: int64

:

In [67]:
print(d_sr["a"])

10

:

## creating data frame from series

In [68]:
name = ["alice", "bob", "carol"]
age = [10, 20, 30]
series1 = pd.Series(name)
series2 = pd.Series(age)
df_s = pd.DataFrame({"name" : series1, "age" : series2})
df_s

    name  age
0  alice   10
1    bob   20
2  carol   30

:

## Transforming to data frame from inbuilt datas

### list

In [69]:
lst = [["Alice", 25],
       ["Bob", 30],
       ["Charlie", 28]]

:

In [70]:
list_df = pd.DataFrame(lst, columns=["Name", "Age"],index=[1, 2, 3])
print(list_df)
print()
print(type(list_df))

      Name  Age
1    Alice   25
2      Bob   30
3  Charlie   28

<class 'pandas.core.frame.DataFrame'>

Name    object
Age      int64
dtype: object

:

In [71]:
list_df

      Name  Age
1    Alice   25
2      Bob   30
3  Charlie   28

:

### tuple

In [72]:
tup = (("Alice", 25),
       ("Bob", 30),
       ("Charlie", 28))

:

In [73]:
tup_df = pd.DataFrame(tup, columns=["Name", "Age"], index=[1,2,3])
print(tup_df)
print()
print(type(tup_df))
print()
print(tup_df.dtypes)

      Name  Age
1    Alice   25
2      Bob   30
3  Charlie   28

<class 'pandas.core.frame.DataFrame'>

Name    object
Age      int64
dtype: object

:

In [74]:
tup_df

      Name  Age
1    Alice   25
2      Bob   30
3  Charlie   28

:

### dictionary

In [75]:
dic = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 28],
}

:

In [76]:
dic_df = pd.DataFrame(dic)
print(dic_df)
print()
print(type(dic_df))
print()
print(dic_df.dtypes)

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   28

<class 'pandas.core.frame.DataFrame'>

Name    object
Age      int64
dtype: object

:

In [77]:
dic_df

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   28

:

### dictionary within a list

In [78]:
l = [
    {"Name": "Alice", "Age": 25, "City": "New York"},
    {"Name": "Bob", "Age": 30, "City": "New York"},
    {"Name": "Charlie", "Age": 28},
]

:

In [79]:
l_df = pd.DataFrame(l)
print(l_df)
print()
print(type(l_df))
print()
print(l_df.dtypes)

      Name  Age      City
0    Alice   25  New York
1      Bob   30  New York
2  Charlie   28       NaN

<class 'pandas.core.frame.DataFrame'>

Name    object
Age      int64
City    object
dtype: object

:

In [80]:
l_df

      Name  Age      City
0    Alice   25  New York
1      Bob   30  New York
2  Charlie   28       NaN

:

## Accessing values from data frame

### accessing a column
a number of series creates a data frame

In [81]:
full_name = df["FullName"]
print(full_name, type(full_name), full_name.dtype)

0          Alif Rahman
1        Fatima Akhter
2        Imran Hossain
3     Jannatul Ferdous
4          Kamal Uddin
5          Laila Begum
6       Mahmudul Hasan
7          Nadia Islam
8           Omar Faruq
9         Priya Sharma
10        Rahim Sheikh
11     Sadia Chowdhury
12        Tanvir Ahmed
13          Urmi Akter
14        Wahiduzzaman
15        Ziaur Rahman
16         Afsana Mimi
17         Babul Ahmed
18        Faria Rahman
19          Nasir Khan
Name: FullName, dtype: object <class 'pandas.core.series.Series'> object

:

### loc[row(index), col(features)]
df.loc[ row_start:row_end, col_start:col_end ]

#### single row

In [82]:
df.loc[0]

StudentID                    PH1001
FullName                Alif Rahman
Data Structure Marks           85.0
Algorithm Marks                85.0
Python Marks                   88.0
CompletionStatus          Completed
EnrollmentDate           2024-01-15
Instructor                Mr. Karim
Location                      Dhaka
Name: 0, dtype: object

:

In [83]:
type(df.loc[0])

pandas.core.series.Series

:

#### multiple row

##### using list

In [84]:
df.loc[[2, 3, 19]]

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

:

##### using range

In [85]:
df.loc[3:7]

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram

:

#### column

##### single

In [86]:
df.loc[:, "Python Marks"]

0     88.0
1      NaN
2     85.0
3     82.0
4     95.0
5     78.0
6      NaN
7     85.0
8     76.0
9     88.0
10    91.0
11    87.0
12    79.0
13     NaN
14    84.0
15     NaN
16    93.0
17    85.0
18     NaN
19    89.0
Name: Python Marks, dtype: float64

:

##### multiple

In [87]:
df.loc[:, ["Python Marks", "CompletionStatus"]]

    Python Marks CompletionStatus
0           88.0        Completed
1            NaN      In Progress
2           85.0        Completed
3           82.0        Completed
4           95.0      In Progress
5           78.0        Completed
6            NaN      In Progress
7           85.0        Completed
8           76.0        Completed
9           88.0        Completed
10          91.0      In Progress
11          87.0        Completed
12          79.0        Completed
13           NaN      Not Started
14          84.0        Completed
15           NaN      In Progress
16          93.0        Completed
17          85.0        Completed
18           NaN      Not Started
19          89.0        Completed

:

In [88]:
type(df.loc[:, ["Python Marks", "CompletionStatus"]])
# data frame since it is a collection of series

pandas.core.frame.DataFrame

:

#### row and column

In [89]:
df.loc[3:7,["Data Structure Marks", "Algorithm Marks", "Python Marks", "CompletionStatus"]]

   Data Structure Marks  Algorithm Marks  Python Marks CompletionStatus
3                  78.0             78.0          82.0        Completed
4                   NaN              NaN          95.0      In Progress
5                  75.0             75.0          78.0        Completed
6                  80.0             80.0           NaN      In Progress
7                  81.0             81.0          85.0        Completed

:

### iat(row, col)

In [90]:
df.iat[0, 0]    # oth row, oth col
# df.iat[0, 1]    # 0th row, 1st col

'PH1001'

:

## Changing index

In [91]:
df2 = df.set_index("StudentID")    # if we want to make this change to the original df, then we will have to pass the parameter
df2                                # inplace = True within the set_index method

,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
StudentID,,,,,,,,
PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

:

### iloc

In [92]:
df2.iloc[3:7, 1:5]

,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus
StudentID,,,,
PH1004,78.0,78.0,82.0,Completed
PH1005,NaN,NaN,95.0,In Progress
PH1006,75.0,75.0,78.0,Completed
PH1007,80.0,80.0,NaN,In Progress

:

## Renaming columns

In [93]:
df3 = df2.rename(columns={"FullName" : "Full Name"})
df3
# need to pass the parameter inplace = True if we intend to change the original data frame

,Full Name,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
StudentID,,,,,,,,
PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

:

## Adding columns

In [94]:
df["Salary"] = 0
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Salary
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,0
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,0
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,0
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,0
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,0
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,0
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka,0
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,0
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,0
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,0
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,0
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,0
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,0
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi,0
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,0
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram,0
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,0
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,0
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram,0
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,0

:

## dropping rows and columns
drop()

In [95]:
df3.drop("PH1001", inplace=True)
df3

,Full Name,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
StudentID,,,,,,,,
PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

:

In [96]:
df3.drop("Location", axis=1, inplace=True)
df3

,Full Name,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor
StudentID,,,,,,,
PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma
PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim
PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma
PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim
PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma
PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim
PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma
PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David
PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma
PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim
PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma
PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David
PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma
PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim
PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma
PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim
PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma
PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David
PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma

:

## assigning or changing marks

In [97]:
# df3.loc[0, "Python Marks"] = 90
df3.iloc[0, 3] = 90
# df3.loc[0, "CompletionStatus"] = "Completed"
df3.iloc[0, 4] = "Completed"
df3

,Full Name,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor
StudentID,,,,,,,
PH1002,Fatima Akhter,92.0,92.0,90.0,Completed,2024-01-20,Ms. Salma
PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim
PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma
PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim
PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma
PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim
PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma
PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David
PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma
PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim
PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma
PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David
PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma
PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim
PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma
PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim
PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma
PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David
PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma

:

In [98]:
# df3.loc[0:3, "Python Marks"] += 1
df3.iloc[0:3, 3] += 1
df3

,Full Name,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor
StudentID,,,,,,,
PH1002,Fatima Akhter,92.0,92.0,91.0,Completed,2024-01-20,Ms. Salma
PH1003,Imran Hossain,88.0,88.0,86.0,Completed,2024-02-10,Mr. Karim
PH1004,Jannatul Ferdous,78.0,78.0,83.0,Completed,2024-02-12,Ms. Salma
PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim
PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma
PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim
PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma
PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David
PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma
PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim
PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma
PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David
PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma
PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim
PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma
PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim
PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma
PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David
PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma

:

## looping through a data frame

### iterrows()

In [99]:
for i, series in df.iterrows():
    print(f"{i} -----> {series}")
# provides series from each row

0 -----> StudentID                    PH1001
FullName                Alif Rahman
Data Structure Marks           85.0
Algorithm Marks                85.0
Python Marks                   88.0
CompletionStatus          Completed
EnrollmentDate           2024-01-15
Instructor                Mr. Karim
Location                      Dhaka
Salary                            0
Name: 0, dtype: object
1 -----> StudentID                      PH1002
FullName                Fatima Akhter
Data Structure Marks             92.0
Algorithm Marks                  92.0
Python Marks                      NaN
CompletionStatus          In Progress
EnrollmentDate             2024-01-20
Instructor                  Ms. Salma
Location                   Chattogram
Salary                              0
Name: 1, dtype: object
2 -----> StudentID                      PH1003
FullName                Imran Hossain
Data Structure Marks             88.0
Algorithm Marks                  88.0
Python Marks                     85.0
CompletionStatus            Completed
EnrollmentDate             2024-02-10
Instructor                  Mr. Karim
Location                        Dhaka
Salary                              0
Name: 2, dtype: object
3 -----> StudentID                         PH1004
FullName                Jannatul Ferdous
Data Structure Marks                78.0
Algorithm Marks                     78.0
Python Marks                        82.0
CompletionStatus               Completed
EnrollmentDate                2024-02-12
Instructor                     Ms. Salma
Location                          Sylhet
Salary                                 0
Name: 3, dtype: object
4 -----> StudentID                    PH1005
FullName                Kamal Uddin
Data Structure Marks            NaN
Algorithm Marks                 NaN
Python Marks                   95.0
CompletionStatus        In Progress
EnrollmentDate           2024-03-05
Instructor                Mr. Karim
Location                 Chattogram
Salary                            0
Name: 4, dtype: object
5 -----> StudentID                    PH1006
FullName                Laila Begum
Data Structure Marks           75.0
Algorithm Marks                75.0
Python Marks                   78.0
CompletionStatus          Completed
EnrollmentDate           2024-03-08
Instructor                Ms. Salma
Location                   Rajshahi
Salary                            0
Name: 5, dtype: object
6 -----> StudentID                       PH1007
FullName                Mahmudul Hasan
Data Structure Marks              80.0
Algorithm Marks                   80.0
Python Marks                       NaN
CompletionStatus           In Progress
EnrollmentDate              2024-04-01
Instructor                   Mr. Karim
Location                         Dhaka
Salary                               0
Name: 6, dtype: object
7 -----> StudentID                    PH1008
FullName                Nadia Islam
Data Structure Marks           81.0
Algorithm Marks                81.0
Python Marks                   85.0
CompletionStatus          Completed
EnrollmentDate           2024-04-22
Instructor                Ms. Salma
Location                 Chattogram
Salary                            0
Name: 7, dtype: object
8 -----> StudentID                   PH1009
FullName                Omar Faruq
Data Structure Marks          72.0
Algorithm Marks               72.0
Python Marks                  76.0
CompletionStatus         Completed
EnrollmentDate          2024-05-16
Instructor               Mr. David
Location                     Dhaka
Salary                           0
Name: 8, dtype: object
9 -----> StudentID                     PH1010
FullName                Priya Sharma
Data Structure Marks            89.0
Algorithm Marks                 89.0
Python Marks                    88.0
CompletionStatus           Completed
EnrollmentDate            2024-05-20
Instructor                 Ms. Salma
Location                      Sylhet
Salary                             0
Name: 9, dtype: object
10 -----> StudentID                     PH1011
FullName                Rahim Sheikh
Data Structure Marks             NaN
Algorithm Marks                  NaN
Python Marks                    91.0
CompletionStatus         In Progress
EnrollmentDate            2024-06-11
Instructor                 Mr. Karim
Location                      Khulna
Salary                             0
Name: 10, dtype: object
11 -----> StudentID                        PH1012
FullName                Sadia Chowdhury
Data Structure Marks               85.0
Algorithm Marks                    85.0
Python Marks                       87.0
CompletionStatus              Completed
EnrollmentDate               2024-06-14
Instructor                    Ms. Salma
Location                     Chattogram
Salary                                0
Name: 11, dtype: object
12 -----> StudentID                     PH1013
FullName                Tanvir Ahmed
Data Structure Marks            75.0
Algorithm Marks                 75.0
Python Marks                    79.0
CompletionStatus           Completed
EnrollmentDate            2024-07-02
Instructor                 Mr. David
Location                       Dhaka
Salary                             0
Name: 12, dtype: object
13 -----> StudentID                    PH1014
FullName                 Urmi Akter
Data Structure Marks            NaN
Algorithm Marks                 NaN
Python Marks                    NaN
CompletionStatus        Not Started
EnrollmentDate           2024-07-09
Instructor                Ms. Salma
Location                   Rajshahi
Salary                            0
Name: 13, dtype: object
14 -----> StudentID                     PH1015
FullName                Wahiduzzaman
Data Structure Marks            86.0
Algorithm Marks                 86.0
Python Marks                    84.0
CompletionStatus           Completed
EnrollmentDate            2024-08-18
Instructor                 Mr. Karim
Location                       Dhaka
Salary                             0
Name: 14, dtype: object
15 -----> StudentID                     PH1016
FullName                Ziaur Rahman
Data Structure Marks            94.0
Algorithm Marks                 94.0
Python Marks                     NaN
CompletionStatus         In Progress
EnrollmentDate            2024-08-21
Instructor                 Ms. Salma
Location                  Chattogram
Salary                             0
Name: 15, dtype: object
16 -----> StudentID                    PH1017
FullName                Afsana Mimi
Data Structure Marks           90.0
Algorithm Marks                90.0
Python Marks                   93.0
CompletionStatus          Completed
EnrollmentDate           2025-09-01
Instructor                Mr. Karim
Location                      Dhaka
Salary                            0
Name: 16, dtype: object
17 -----> StudentID                    PH1018
FullName                Babul Ahmed
Data Structure Marks           88.0
Algorithm Marks                88.0
Python Marks                   85.0
CompletionStatus          Completed
EnrollmentDate           2025-09-05
Instructor                Ms. Salma
Location                     Sylhet
Salary                            0
Name: 17, dtype: object
18 -----> StudentID                     PH1019
FullName                Faria Rahman
Data Structure Marks             NaN
Algorithm Marks                  NaN
Python Marks                     NaN
CompletionStatus         Not Started
EnrollmentDate            2025-09-15
Instructor                 Mr. David
Location                  Chattogram
Salary                             0
Name: 18, dtype: object
19 -----> StudentID                   PH1020
FullName                Nasir Khan
Data Structure Marks          86.0
Algorithm Marks               86.0
Python Marks                  89.0
CompletionStatus         Completed
EnrollmentDate          2025-10-02
Instructor               Ms. Salma
Location                     Dhaka
Salary                           0
Name: 19, dtype: object

:

### itertuples()
faster method

In [100]:
for i in df.itertuples():
    print(i)

Pandas(Index=0, StudentID='PH1001', FullName='Alif Rahman', _3=85.0, _4=85.0, _5=88.0, CompletionStatus='Completed', EnrollmentDate='2024-01-15', Instructor='Mr. Karim', Location='Dhaka', Salary=0)
Pandas(Index=1, StudentID='PH1002', FullName='Fatima Akhter', _3=92.0, _4=92.0, _5=nan, CompletionStatus='In Progress', EnrollmentDate='2024-01-20', Instructor='Ms. Salma', Location='Chattogram', Salary=0)
Pandas(Index=2, StudentID='PH1003', FullName='Imran Hossain', _3=88.0, _4=88.0, _5=85.0, CompletionStatus='Completed', EnrollmentDate='2024-02-10', Instructor='Mr. Karim', Location='Dhaka', Salary=0)
Pandas(Index=3, StudentID='PH1004', FullName='Jannatul Ferdous', _3=78.0, _4=78.0, _5=82.0, CompletionStatus='Completed', EnrollmentDate='2024-02-12', Instructor='Ms. Salma', Location='Sylhet', Salary=0)
Pandas(Index=4, StudentID='PH1005', FullName='Kamal Uddin', _3=nan, _4=nan, _5=95.0, CompletionStatus='In Progress', EnrollmentDate='2024-03-05', Instructor='Mr. Karim', Location='Chattogram', Salary=0)
Pandas(Index=5, StudentID='PH1006', FullName='Laila Begum', _3=75.0, _4=75.0, _5=78.0, CompletionStatus='Completed', EnrollmentDate='2024-03-08', Instructor='Ms. Salma', Location='Rajshahi', Salary=0)
Pandas(Index=6, StudentID='PH1007', FullName='Mahmudul Hasan', _3=80.0, _4=80.0, _5=nan, CompletionStatus='In Progress', EnrollmentDate='2024-04-01', Instructor='Mr. Karim', Location='Dhaka', Salary=0)
Pandas(Index=7, StudentID='PH1008', FullName='Nadia Islam', _3=81.0, _4=81.0, _5=85.0, CompletionStatus='Completed', EnrollmentDate='2024-04-22', Instructor='Ms. Salma', Location='Chattogram', Salary=0)
Pandas(Index=8, StudentID='PH1009', FullName='Omar Faruq', _3=72.0, _4=72.0, _5=76.0, CompletionStatus='Completed', EnrollmentDate='2024-05-16', Instructor='Mr. David', Location='Dhaka', Salary=0)
Pandas(Index=9, StudentID='PH1010', FullName='Priya Sharma', _3=89.0, _4=89.0, _5=88.0, CompletionStatus='Completed', EnrollmentDate='2024-05-20', Instructor='Ms. Salma', Location='Sylhet', Salary=0)
Pandas(Index=10, StudentID='PH1011', FullName='Rahim Sheikh', _3=nan, _4=nan, _5=91.0, CompletionStatus='In Progress', EnrollmentDate='2024-06-11', Instructor='Mr. Karim', Location='Khulna', Salary=0)
Pandas(Index=11, StudentID='PH1012', FullName='Sadia Chowdhury', _3=85.0, _4=85.0, _5=87.0, CompletionStatus='Completed', EnrollmentDate='2024-06-14', Instructor='Ms. Salma', Location='Chattogram', Salary=0)
Pandas(Index=12, StudentID='PH1013', FullName='Tanvir Ahmed', _3=75.0, _4=75.0, _5=79.0, CompletionStatus='Completed', EnrollmentDate='2024-07-02', Instructor='Mr. David', Location='Dhaka', Salary=0)
Pandas(Index=13, StudentID='PH1014', FullName='Urmi Akter', _3=nan, _4=nan, _5=nan, CompletionStatus='Not Started', EnrollmentDate='2024-07-09', Instructor='Ms. Salma', Location='Rajshahi', Salary=0)
Pandas(Index=14, StudentID='PH1015', FullName='Wahiduzzaman', _3=86.0, _4=86.0, _5=84.0, CompletionStatus='Completed', EnrollmentDate='2024-08-18', Instructor='Mr. Karim', Location='Dhaka', Salary=0)
Pandas(Index=15, StudentID='PH1016', FullName='Ziaur Rahman', _3=94.0, _4=94.0, _5=nan, CompletionStatus='In Progress', EnrollmentDate='2024-08-21', Instructor='Ms. Salma', Location='Chattogram', Salary=0)
Pandas(Index=16, StudentID='PH1017', FullName='Afsana Mimi', _3=90.0, _4=90.0, _5=93.0, CompletionStatus='Completed', EnrollmentDate='2025-09-01', Instructor='Mr. Karim', Location='Dhaka', Salary=0)
Pandas(Index=17, StudentID='PH1018', FullName='Babul Ahmed', _3=88.0, _4=88.0, _5=85.0, CompletionStatus='Completed', EnrollmentDate='2025-09-05', Instructor='Ms. Salma', Location='Sylhet', Salary=0)
Pandas(Index=18, StudentID='PH1019', FullName='Faria Rahman', _3=nan, _4=nan, _5=nan, CompletionStatus='Not Started', EnrollmentDate='2025-09-15', Instructor='Mr. David', Location='Chattogram', Salary=0)
Pandas(Index=19, StudentID='PH1020', FullName='Nasir Khan', _3=86.0, _4=86.0, _5=89.0, CompletionStatus='Completed', EnrollmentDate='2025-10-02', Instructor='Ms. Salma', Location='Dhaka', Salary=0)

:

In [101]:
for i in df.itertuples(index=False):
    print(i)

Pandas(StudentID='PH1001', FullName='Alif Rahman', _2=85.0, _3=85.0, _4=88.0, CompletionStatus='Completed', EnrollmentDate='2024-01-15', Instructor='Mr. Karim', Location='Dhaka', Salary=0)
Pandas(StudentID='PH1002', FullName='Fatima Akhter', _2=92.0, _3=92.0, _4=nan, CompletionStatus='In Progress', EnrollmentDate='2024-01-20', Instructor='Ms. Salma', Location='Chattogram', Salary=0)
Pandas(StudentID='PH1003', FullName='Imran Hossain', _2=88.0, _3=88.0, _4=85.0, CompletionStatus='Completed', EnrollmentDate='2024-02-10', Instructor='Mr. Karim', Location='Dhaka', Salary=0)
Pandas(StudentID='PH1004', FullName='Jannatul Ferdous', _2=78.0, _3=78.0, _4=82.0, CompletionStatus='Completed', EnrollmentDate='2024-02-12', Instructor='Ms. Salma', Location='Sylhet', Salary=0)
Pandas(StudentID='PH1005', FullName='Kamal Uddin', _2=nan, _3=nan, _4=95.0, CompletionStatus='In Progress', EnrollmentDate='2024-03-05', Instructor='Mr. Karim', Location='Chattogram', Salary=0)
Pandas(StudentID='PH1006', FullName='Laila Begum', _2=75.0, _3=75.0, _4=78.0, CompletionStatus='Completed', EnrollmentDate='2024-03-08', Instructor='Ms. Salma', Location='Rajshahi', Salary=0)
Pandas(StudentID='PH1007', FullName='Mahmudul Hasan', _2=80.0, _3=80.0, _4=nan, CompletionStatus='In Progress', EnrollmentDate='2024-04-01', Instructor='Mr. Karim', Location='Dhaka', Salary=0)
Pandas(StudentID='PH1008', FullName='Nadia Islam', _2=81.0, _3=81.0, _4=85.0, CompletionStatus='Completed', EnrollmentDate='2024-04-22', Instructor='Ms. Salma', Location='Chattogram', Salary=0)
Pandas(StudentID='PH1009', FullName='Omar Faruq', _2=72.0, _3=72.0, _4=76.0, CompletionStatus='Completed', EnrollmentDate='2024-05-16', Instructor='Mr. David', Location='Dhaka', Salary=0)
Pandas(StudentID='PH1010', FullName='Priya Sharma', _2=89.0, _3=89.0, _4=88.0, CompletionStatus='Completed', EnrollmentDate='2024-05-20', Instructor='Ms. Salma', Location='Sylhet', Salary=0)
Pandas(StudentID='PH1011', FullName='Rahim Sheikh', _2=nan, _3=nan, _4=91.0, CompletionStatus='In Progress', EnrollmentDate='2024-06-11', Instructor='Mr. Karim', Location='Khulna', Salary=0)
Pandas(StudentID='PH1012', FullName='Sadia Chowdhury', _2=85.0, _3=85.0, _4=87.0, CompletionStatus='Completed', EnrollmentDate='2024-06-14', Instructor='Ms. Salma', Location='Chattogram', Salary=0)
Pandas(StudentID='PH1013', FullName='Tanvir Ahmed', _2=75.0, _3=75.0, _4=79.0, CompletionStatus='Completed', EnrollmentDate='2024-07-02', Instructor='Mr. David', Location='Dhaka', Salary=0)
Pandas(StudentID='PH1014', FullName='Urmi Akter', _2=nan, _3=nan, _4=nan, CompletionStatus='Not Started', EnrollmentDate='2024-07-09', Instructor='Ms. Salma', Location='Rajshahi', Salary=0)
Pandas(StudentID='PH1015', FullName='Wahiduzzaman', _2=86.0, _3=86.0, _4=84.0, CompletionStatus='Completed', EnrollmentDate='2024-08-18', Instructor='Mr. Karim', Location='Dhaka', Salary=0)
Pandas(StudentID='PH1016', FullName='Ziaur Rahman', _2=94.0, _3=94.0, _4=nan, CompletionStatus='In Progress', EnrollmentDate='2024-08-21', Instructor='Ms. Salma', Location='Chattogram', Salary=0)
Pandas(StudentID='PH1017', FullName='Afsana Mimi', _2=90.0, _3=90.0, _4=93.0, CompletionStatus='Completed', EnrollmentDate='2025-09-01', Instructor='Mr. Karim', Location='Dhaka', Salary=0)
Pandas(StudentID='PH1018', FullName='Babul Ahmed', _2=88.0, _3=88.0, _4=85.0, CompletionStatus='Completed', EnrollmentDate='2025-09-05', Instructor='Ms. Salma', Location='Sylhet', Salary=0)
Pandas(StudentID='PH1019', FullName='Faria Rahman', _2=nan, _3=nan, _4=nan, CompletionStatus='Not Started', EnrollmentDate='2025-09-15', Instructor='Mr. David', Location='Chattogram', Salary=0)
Pandas(StudentID='PH1020', FullName='Nasir Khan', _2=86.0, _3=86.0, _4=89.0, CompletionStatus='Completed', EnrollmentDate='2025-10-02', Instructor='Ms. Salma', Location='Dhaka', Salary=0)

:

## Sorting
sort_values()

In [102]:
# sorted values in ascending order
ascdf = df3.sort_values("Data Structure Marks")
ascdf

,Full Name,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor
StudentID,,,,,,,
PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David
PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma
PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David
PH1004,Jannatul Ferdous,78.0,78.0,83.0,Completed,2024-02-12,Ms. Salma
PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim
PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma
PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma
PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim
PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma
PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma
PH1003,Imran Hossain,88.0,88.0,86.0,Completed,2024-02-10,Mr. Karim
PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma
PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim
PH1002,Fatima Akhter,92.0,92.0,91.0,Completed,2024-01-20,Ms. Salma
PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma
PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim
PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim
PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma
PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David

:

In [103]:
# sorted values in descending order
dscdf = df3.sort_values("Data Structure Marks", ascending=False)
dscdf

,Full Name,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor
StudentID,,,,,,,
PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma
PH1002,Fatima Akhter,92.0,92.0,91.0,Completed,2024-01-20,Ms. Salma
PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim
PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma
PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma
PH1003,Imran Hossain,88.0,88.0,86.0,Completed,2024-02-10,Mr. Karim
PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim
PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma
PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma
PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma
PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim
PH1004,Jannatul Ferdous,78.0,78.0,83.0,Completed,2024-02-12,Ms. Salma
PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma
PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David
PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David
PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim
PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim
PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma
PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David

:

In [104]:
# firstly, the data frame will get sorted upon data structure marks, 
# but for any rows if the data structure marks happens to be the same, then
# it will get sorted upon algorithm marks
orderdf = df3.sort_values(["Data Structure Marks", "Algorithm Marks"], ascending=False)
orderdf

,Full Name,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor
StudentID,,,,,,,
PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma
PH1002,Fatima Akhter,92.0,92.0,91.0,Completed,2024-01-20,Ms. Salma
PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim
PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma
PH1003,Imran Hossain,88.0,88.0,86.0,Completed,2024-02-10,Mr. Karim
PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma
PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim
PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma
PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma
PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma
PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim
PH1004,Jannatul Ferdous,78.0,78.0,83.0,Completed,2024-02-12,Ms. Salma
PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma
PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David
PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David
PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim
PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim
PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma
PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David

:

In [105]:
# firstly, the data frame will get sorted upon data structure marks in descending order, 
# but for any rows if the data structure marks happens to be the same, then
# it will get sorted in ascending order upon algorithm marks
orderdf = df3.sort_values(["Data Structure Marks", "Algorithm Marks"], ascending=[0, 1])
orderdf

,Full Name,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor
StudentID,,,,,,,
PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma
PH1002,Fatima Akhter,92.0,92.0,91.0,Completed,2024-01-20,Ms. Salma
PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim
PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma
PH1003,Imran Hossain,88.0,88.0,86.0,Completed,2024-02-10,Mr. Karim
PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma
PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim
PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma
PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma
PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma
PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim
PH1004,Jannatul Ferdous,78.0,78.0,83.0,Completed,2024-02-12,Ms. Salma
PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma
PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David
PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David
PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim
PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim
PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma
PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David

:

## incrementing a column by n

In [108]:
df["Python Marks"] += 1

:

In [109]:
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Salary
0,PH1001,Alif Rahman,85.0,85.0,90.0,Completed,2024-01-15,Mr. Karim,Dhaka,0
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,0
2,PH1003,Imran Hossain,88.0,88.0,87.0,Completed,2024-02-10,Mr. Karim,Dhaka,0
3,PH1004,Jannatul Ferdous,78.0,78.0,84.0,Completed,2024-02-12,Ms. Salma,Sylhet,0
4,PH1005,Kamal Uddin,NaN,NaN,97.0,In Progress,2024-03-05,Mr. Karim,Chattogram,0
5,PH1006,Laila Begum,75.0,75.0,80.0,Completed,2024-03-08,Ms. Salma,Rajshahi,0
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka,0
7,PH1008,Nadia Islam,81.0,81.0,87.0,Completed,2024-04-22,Ms. Salma,Chattogram,0
8,PH1009,Omar Faruq,72.0,72.0,78.0,Completed,2024-05-16,Mr. David,Dhaka,0
9,PH1010,Priya Sharma,89.0,89.0,90.0,Completed,2024-05-20,Ms. Salma,Sylhet,0
10,PH1011,Rahim Sheikh,NaN,NaN,93.0,In Progress,2024-06-11,Mr. Karim,Khulna,0
11,PH1012,Sadia Chowdhury,85.0,85.0,89.0,Completed,2024-06-14,Ms. Salma,Chattogram,0
12,PH1013,Tanvir Ahmed,75.0,75.0,81.0,Completed,2024-07-02,Mr. David,Dhaka,0
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi,0
14,PH1015,Wahiduzzaman,86.0,86.0,86.0,Completed,2024-08-18,Mr. Karim,Dhaka,0
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram,0
16,PH1017,Afsana Mimi,90.0,90.0,95.0,Completed,2025-09-01,Mr. Karim,Dhaka,0
17,PH1018,Babul Ahmed,88.0,88.0,87.0,Completed,2025-09-05,Ms. Salma,Sylhet,0
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram,0
19,PH1020,Nasir Khan,86.0,86.0,91.0,Completed,2025-10-02,Ms. Salma,Dhaka,0

:

## null values
isnull()

In [123]:
df.isnull()    # True indicates the data to be null

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,True,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,True,True,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False
6,False,False,False,False,True,False,False,False,False
7,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False
10,False,False,True,True,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False
13,False,False,True,True,True,False,False,False,False
14,False,False,False,False,False,False,False,False,False
15,False,False,False,False,True,False,False,False,False
16,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False
18,False,False,True,True,True,False,False,False,False
19,False,False,False,False,False,False,False,False,False

:

In [126]:
df.isnull().sum()    # counts the number of null values present within each column

StudentID               0
FullName                0
Data Structure Marks    4
Algorithm Marks         4
Python Marks            5
CompletionStatus        0
EnrollmentDate          0
Instructor              0
Location                0
dtype: int64

:

### notnull()
returns true if the element is not a null value

In [37]:
df["Data Structure Marks"].notnull()

0      True
1      True
2      True
3      True
4     False
5      True
6      True
7      True
8      True
9      True
10    False
11     True
12     True
13    False
14     True
15     True
16     True
17     True
18    False
19     True
Name: Data Structure Marks, dtype: bool

:

### hasnans
returns true if there is atleast one element within the series with a null value

In [39]:
df["Data Structure Marks"].hasnans

True

:

### filling up the null values with a number

In [125]:
df.fillna(0)    # the null values are replaced with zero

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,0.0,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,0.0,0.0,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,0.0,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,0.0,0.0,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,0.0,0.0,0.0,Not Started,2024-07-09,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,0.0,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,0.0,0.0,0.0,Not Started,2025-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

:

In [12]:
# filling the nan values of the series FullName with the string unknown
df["FullName"].fillna("unknown")

0          Alif Rahman
1        Fatima Akhter
2        Imran Hossain
3     Jannatul Ferdous
4          Kamal Uddin
5          Laila Begum
6       Mahmudul Hasan
7          Nadia Islam
8           Omar Faruq
9         Priya Sharma
10        Rahim Sheikh
11     Sadia Chowdhury
12        Tanvir Ahmed
13          Urmi Akter
14        Wahiduzzaman
15        Ziaur Rahman
16         Afsana Mimi
17         Babul Ahmed
18        Faria Rahman
19          Nasir Khan
20             unknown
Name: FullName, dtype: object

In [135]:
df["Python_Marks_not_null"] = df["Python Marks"].fillna(df["Python Marks"].mean())
# mean value is getting placed instead of null

:

In [136]:
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Python_Marks_not_null
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,88.000000
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,85.666667
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,85.000000
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,82.000000
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,95.000000
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,78.000000
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka,85.666667
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,85.000000
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,76.000000
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,88.000000
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,91.000000
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,87.000000
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,79.000000
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi,85.666667
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,84.000000
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram,85.666667
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,93.000000
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,85.000000
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram,85.666667
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,89.000000

:

## apply()

In [137]:
df["Python Marks doubled"] = df["Python Marks"].apply(lambda x : x ** 2) 
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Python_Marks_not_null,Python Marks doubled
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,88.000000,7744.0
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,85.666667,NaN
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,85.000000,7225.0
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,82.000000,6724.0
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,95.000000,9025.0
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,78.000000,6084.0
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka,85.666667,NaN
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,85.000000,7225.0
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,76.000000,5776.0
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,88.000000,7744.0
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,91.000000,8281.0
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,87.000000,7569.0
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,79.000000,6241.0
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi,85.666667,NaN
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,84.000000,7056.0
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram,85.666667,NaN
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,93.000000,8649.0
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,85.000000,7225.0
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram,85.666667,NaN
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,89.000000,7921.0

:

### min-max scaling

In [30]:
min = df["Total Marks"].min()
max = df["Total Marks"].max()

df["Scaled Marks"] = df["Total Marks"].apply(lambda x : (x-min)/(max-min))

df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Total Marks,Scaled Marks
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,258.0,0.945055
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,184.0,0.673993
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,261.0,0.956044
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,238.0,0.871795
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,95.0,0.347985
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,228.0,0.835165
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka,160.0,0.586081
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,247.0,0.904762
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,220.0,0.805861
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,266.0,0.974359
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,91.0,0.333333
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,257.0,0.941392
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,229.0,0.838828
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi,0.0,0.000000
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,256.0,0.937729
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram,188.0,0.688645
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,273.0,1.000000
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,261.0,0.956044
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram,0.0,0.000000
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,261.0,0.956044
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.000000

In [34]:
def grading(x):
    if x >= 250:
        return "A+"
    elif x >= 200:
        return "A"
    else:
        return "P"
    
df["Grade"] = df["Total Marks"].apply(grading)

df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Total Marks,Scaled Marks,Grade
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,258.0,0.945055,A+
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,184.0,0.673993,P
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,261.0,0.956044,A+
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,238.0,0.871795,A
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,95.0,0.347985,P
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,228.0,0.835165,A
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka,160.0,0.586081,P
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,247.0,0.904762,A
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,220.0,0.805861,A
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,266.0,0.974359,A+
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,91.0,0.333333,P
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,257.0,0.941392,A+
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,229.0,0.838828,A
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi,0.0,0.000000,P
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,256.0,0.937729,A+
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram,188.0,0.688645,P
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,273.0,1.000000,A+
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,261.0,0.956044,A+
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram,0.0,0.000000,P
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,261.0,0.956044,A+
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.000000,P

In [36]:
def totalMarks(df):
    return df["Data Structure Marks"] + df["Algorithm Marks"] + df["Python Marks"]

df["Total Marks 2"] = df.apply(totalMarks, axis=1)

df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Total Marks,Scaled Marks,Grade,Total Marks 2
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,258.0,0.945055,A+,258.0
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,184.0,0.673993,P,NaN
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,261.0,0.956044,A+,261.0
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,238.0,0.871795,A,238.0
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,95.0,0.347985,P,NaN
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,228.0,0.835165,A,228.0
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka,160.0,0.586081,P,NaN
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,247.0,0.904762,A,247.0
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,220.0,0.805861,A,220.0
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,266.0,0.974359,A+,266.0
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,91.0,0.333333,P,NaN
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,257.0,0.941392,A+,257.0
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,229.0,0.838828,A,229.0
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi,0.0,0.000000,P,NaN
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,256.0,0.937729,A+,256.0
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram,188.0,0.688645,P,NaN
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,273.0,1.000000,A+,273.0
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,261.0,0.956044,A+,261.0
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram,0.0,0.000000,P,NaN
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,261.0,0.956044,A+,261.0
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.000000,P,NaN

In [138]:
df[df["Instructor"] == "Mr. Karim"]

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Python_Marks_not_null,Python Marks doubled
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,88.000000,7744.0
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,85.000000,7225.0
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,95.000000,9025.0
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka,85.666667,NaN
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,91.000000,8281.0
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,84.000000,7056.0
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,93.000000,8649.0

:

In [143]:
df[(df["Instructor"] == "Mr. Karim") & (df["CompletionStatus"] == "Completed")]

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Python_Marks_not_null,Python Marks doubled
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,88.0,7744.0
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,85.0,7225.0
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,84.0,7056.0
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,93.0,8649.0

:

In [145]:
df[~(df["Location"] == "Dhaka")]

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Python_Marks_not_null,Python Marks doubled
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,85.666667,NaN
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,82.000000,6724.0
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,95.000000,9025.0
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,78.000000,6084.0
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,85.000000,7225.0
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,88.000000,7744.0
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,91.000000,8281.0
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,87.000000,7569.0
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi,85.666667,NaN
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram,85.666667,NaN
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,85.000000,7225.0
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram,85.666667,NaN

:

## Finding unique values from a series (column)
unique()

In [148]:
# unique() only works in series
instructors = df["Instructor"].unique()
print(instructors, type(instructors), instructors.dtype)

['Mr. Karim' 'Ms. Salma' 'Mr. David'] <class 'numpy.ndarray'> object

:

### nunique()
only shows the number of unique values excluding null values

In [36]:
print(f"Showing unique values in Data Structure marks including null value: {len(df["Data Structure Marks"].unique())}")
print(f"Showing the number of unique values only in Data Structure Marks: {df["Data Structure Marks"].nunique()}")

Showing unique values in Data Structure marks including null value: 13
Showing the number of unique values only in Data Structure Marks: 12

:

In [31]:
df["Total Marks"] = df["Data Structure Marks"] + df["Algorithm Marks"] + df["Python Marks"]
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Total Marks
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,258.0
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,NaN
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,261.0
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,238.0
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,NaN
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,228.0
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka,NaN
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,247.0
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,220.0
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,266.0
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,NaN
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,257.0
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,229.0
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi,NaN
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,256.0
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram,NaN
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,273.0
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,261.0
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram,NaN
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,261.0

## np.where()

In [32]:
df["result"] = np.where(df["Total Marks"] > 256, "Passed", "Failed")
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Total Marks,result
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,258.0,Passed
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,NaN,Failed
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,261.0,Passed
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,238.0,Failed
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,NaN,Failed
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,228.0,Failed
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka,NaN,Failed
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,247.0,Failed
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,220.0,Failed
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,266.0,Passed
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,NaN,Failed
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,257.0,Passed
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,229.0,Failed
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi,NaN,Failed
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,256.0,Failed
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram,NaN,Failed
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,273.0,Passed
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,261.0,Passed
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram,NaN,Failed
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,261.0,Passed

## str.split()

In [33]:
df["First Name"] = df["FullName"].str.split().str[0]
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Total Marks,result,First Name
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,258.0,Passed,Alif
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,NaN,Failed,Fatima
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,261.0,Passed,Imran
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,238.0,Failed,Jannatul
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,NaN,Failed,Kamal
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,228.0,Failed,Laila
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka,NaN,Failed,Mahmudul
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,247.0,Failed,Nadia
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,220.0,Failed,Omar
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,266.0,Passed,Priya
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,NaN,Failed,Rahim
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,257.0,Passed,Sadia
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,229.0,Failed,Tanvir
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi,NaN,Failed,Urmi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,256.0,Failed,Wahiduzzaman
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram,NaN,Failed,Ziaur
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,273.0,Passed,Afsana
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,261.0,Passed,Babul
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram,NaN,Failed,Faria
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,261.0,Passed,Nasir

## Saving the dataframe

In [35]:
# saving as csv file
# df.to_csv("new data.csv")

## Filtering based on string

In [3]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve", "Frank", "Grace", "Hannah","Sakib", "Sakib", "Alice"],
    "City": ["New York", "Los Angeles", "Newark", "Boston", "New Delhi", "Chicago", "New Orleans", "Houston","H Los Ang", "H Los Ang", "H Los Ang"],
    "Department": ["HR", "IT", "Finance", "IT", "HR", "Marketing", "Finance", "HR", "HR", "HR", "HR"],
    "Salary": [50000, 60000, 55000, 70000, 52000, 58000, 62000, 51000,70000, 70000, 70000]
}

df = pd.DataFrame(data)

In [60]:
df

       Name         City Department  Salary
0     Alice     New York         HR   50000
1       Bob  Los Angeles         IT   60000
2   Charlie       Newark    Finance   55000
3     David       Boston         IT   70000
4       Eve    New Delhi         HR   52000
5     Frank      Chicago  Marketing   58000
6     Grace  New Orleans    Finance   62000
7    Hannah      Houston         HR   51000
8     Sakib    H Los Ang         HR   70000
9     Sakib    H Los Ang         HR   70000
10    Alice    H Los Ang         HR   70000

### str.contains()

In [61]:
# only showing cities who have the substring "New" in its name
# case sensitive
df.loc[df["City"].str.contains("new")]

Empty DataFrame
Columns: [Name, City, Department, Salary]
Index: []

In [62]:
# no longer case sensitive as case is set to false
df.loc[df["City"].str.contains("new", case=False)]

      Name         City Department  Salary
0    Alice     New York         HR   50000
2  Charlie       Newark    Finance   55000
4      Eve    New Delhi         HR   52000
6    Grace  New Orleans    Finance   62000

#### regular expression

In [63]:
# city names that start with the substring Los.
df.loc[df["City"].str.contains(r"^los",case=False)]

  Name         City Department  Salary
1  Bob  Los Angeles         IT   60000

In [64]:
# city names that ends with the substring rk.
df.loc[df["City"].str.contains(r"rk$",case=False)]

      Name      City Department  Salary
0    Alice  New York         HR   50000
2  Charlie    Newark    Finance   55000

In [65]:
# names that start with vowel
df.loc[df["Name"].str.contains(r"^[aeiou]", case=False)]

     Name       City Department  Salary
0   Alice   New York         HR   50000
4     Eve  New Delhi         HR   52000
10  Alice  H Los Ang         HR   70000

In [66]:
# city names that contains the substring either new or loss
df.loc[df["City"].str.contains(r"new|los", case=False)]

       Name         City Department  Salary
0     Alice     New York         HR   50000
1       Bob  Los Angeles         IT   60000
2   Charlie       Newark    Finance   55000
4       Eve    New Delhi         HR   52000
6     Grace  New Orleans    Finance   62000
8     Sakib    H Los Ang         HR   70000
9     Sakib    H Los Ang         HR   70000
10    Alice    H Los Ang         HR   70000

## Handling duplicate values

### duplicated()
returns true for the row with duplicate values

In [67]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9      True
10    False
dtype: bool

In [68]:
print(f"Total number of duplicate rows: {df.duplicated().sum()}")

Total number of duplicate rows: 1

### drop_duplicates()
drops duplicate row

In [69]:
# returns a copy unless inplace=True parameter is passed
df.drop_duplicates(inplace=True)
df

       Name         City Department  Salary
0     Alice     New York         HR   50000
1       Bob  Los Angeles         IT   60000
2   Charlie       Newark    Finance   55000
3     David       Boston         IT   70000
4       Eve    New Delhi         HR   52000
5     Frank      Chicago  Marketing   58000
6     Grace  New Orleans    Finance   62000
7    Hannah      Houston         HR   51000
8     Sakib    H Los Ang         HR   70000
10    Alice    H Los Ang         HR   70000

In [71]:
# deleting duplicate rows based on name
df.drop_duplicates(subset=["Name", "City"], inplace=True)
df

      Name         City Department  Salary
0    Alice     New York         HR   50000
1      Bob  Los Angeles         IT   60000
2  Charlie       Newark    Finance   55000
3    David       Boston         IT   70000
4      Eve    New Delhi         HR   52000
5    Frank      Chicago  Marketing   58000
6    Grace  New Orleans    Finance   62000
7   Hannah      Houston         HR   51000
8    Sakib    H Los Ang         HR   70000

### dropna()

#### dropna(how="any")
drop rows with any null values
returns a copy if inplace=True is not passed

In [7]:
df.dropna()

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

#### dropna(how="all")
drops rows with all null values. (for an row to be dropped, every element within that row has to be null) 

returns a copy if inplace=True is not passed

In [8]:
df.dropna(how="all")

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

In [9]:
# drops rows where python mark is null
df.dropna(subset=["Python Marks"])

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

In [10]:
df.dropna(subset=["Python Marks", "Algorithm Marks"])

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

## statistical functions

In [13]:
df["Algorithm Marks"].sum()

np.float64(1344.0)

In [24]:
# row wise summation between the two series. By default axis=0 parameter is there
df[["Data Structure Marks", "Algorithm Marks"]].sum()

Data Structure Marks    1344.0
Algorithm Marks         1344.0
dtype: float64

In [25]:
# column wise summation between the two series
df[["Data Structure Marks", "Algorithm Marks"]].sum(axis=1)

0     170.0
1     184.0
2     176.0
3     156.0
4       0.0
5     150.0
6     160.0
7     162.0
8     144.0
9     178.0
10      0.0
11    170.0
12    150.0
13      0.0
14    172.0
15    188.0
16    180.0
17    176.0
18      0.0
19    172.0
20      0.0
dtype: float64

In [14]:
df["Algorithm Marks"].max()

np.float64(94.0)

In [15]:
df["Algorithm Marks"].min()

np.float64(72.0)

In [16]:
df["Algorithm Marks"].median()

np.float64(85.5)

In [17]:
df["Algorithm Marks"].mode()

0    75.0
1    85.0
2    86.0
3    88.0
Name: Algorithm Marks, dtype: float64

In [18]:
df["Algorithm Marks"].std()

np.float64(6.501281924871945)

In [23]:
df[["Data Structure Marks", "Algorithm Marks"]].corr()

                      Data Structure Marks  Algorithm Marks
Data Structure Marks                   1.0              1.0
Algorithm Marks                        1.0              1.0

In [27]:
df["Total Marks"] = df.iloc[:, 2:5].sum(axis=1)
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Total Marks
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,258.0
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,184.0
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,261.0
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,238.0
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,95.0
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,228.0
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka,160.0
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,247.0
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,220.0
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,266.0
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,91.0
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,257.0
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,229.0
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi,0.0
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,256.0
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram,188.0
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,273.0
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,261.0
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram,0.0
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,261.0
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0

## DateTime and time delta

In [53]:
df = pd.read_csv("student_completed.csv")
df

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks
0,PH0001,Alif Rahman,Completed,2024-09-01,2024-12-23,Ms. Salma,Khulna,300
1,PH0002,Fatima Akhter,Completed,2024-08-11,2024-11-07,Mr. Karim,Dhaka,271
2,PH0003,Imran Hossain,Completed,2024-05-08,2024-08-08,Ms. Salma,Dhaka,269
3,PH0004,Jannatul Ferdous,Completed,2024-07-05,2024-09-23,Mr. Karim,Khulna,270
4,PH0005,Kamal Uddin,Completed,2024-02-01,2024-04-17,Mr. David,Sylhet,254
5,PH0006,Laila Begum,Completed,2024-09-07,2024-12-31,Mr. David,Khulna,272
6,PH0007,Mahmudul Hasan,Completed,2024-06-07,2024-07-20,Mr. David,Chattogram,249
7,PH0008,Nadia Islam,Completed,2024-03-22,2024-05-01,Ms. Salma,Khulna,246
8,PH0009,Omar Faruq,Completed,2024-02-12,2024-06-08,Mr. Karim,Dhaka,291
9,PH0010,Priya Sharma,Completed,2024-06-19,2024-08-19,Mr. David,Dhaka,286
10,PH0011,Rahim Sheikh,Completed,2024-03-14,2024-06-11,Mr. Karim,Sylhet,283
11,PH0012,Sadia Chowdhury,Completed,2024-08-04,2024-10-25,Mr. Karim,Sylhet,266
12,PH0013,Tanvir Ahmed,Completed,2024-06-07,2024-08-03,Mr. David,Dhaka,248
13,PH0014,Urmi Akter,Completed,2024-01-04,2024-03-23,Mr. David,Sylhet,285
14,PH0015,Wahiduzzaman,Completed,2024-02-22,2024-05-16,Mr. David,Rajshahi,291
15,PH0016,Ziaur Rahman,Completed,2024-03-23,2024-06-21,Ms. Salma,Rajshahi,234
16,PH0017,Afsana Mimi,Completed,2024-01-18,2024-03-16,Mr. David,Khulna,236
17,PH0018,Babul Ahmed,Completed,2024-06-23,2024-09-20,Mr. David,Dhaka,278
18,PH0019,Faria Rahman,Completed,2024-04-19,2024-08-17,Mr. Karim,Sylhet,277
19,PH0020,Tariq Hasan,Completed,2024-07-21,2024-10-11,Mr. Karim,Khulna,253

### changing the data type of EnrollmentDate series to datetime

In [54]:
df["EnrollmentDate"]

0     2024-09-01
1     2024-08-11
2     2024-05-08
3     2024-07-05
4     2024-02-01
5     2024-09-07
6     2024-06-07
7     2024-03-22
8     2024-02-12
9     2024-06-19
10    2024-03-14
11    2024-08-04
12    2024-06-07
13    2024-01-04
14    2024-02-22
15    2024-03-23
16    2024-01-18
17    2024-06-23
18    2024-04-19
19    2024-07-21
Name: EnrollmentDate, dtype: object

In [55]:
df["EnrollmentDate"] = pd.to_datetime(df["EnrollmentDate"])
df["FinishedDate"] = pd.to_datetime(df["FinishedDate"])

In [56]:
df["EnrollmentDate"]

0    2024-09-01
1    2024-08-11
2    2024-05-08
3    2024-07-05
4    2024-02-01
5    2024-09-07
6    2024-06-07
7    2024-03-22
8    2024-02-12
9    2024-06-19
10   2024-03-14
11   2024-08-04
12   2024-06-07
13   2024-01-04
14   2024-02-22
15   2024-03-23
16   2024-01-18
17   2024-06-23
18   2024-04-19
19   2024-07-21
Name: EnrollmentDate, dtype: datetime64[ns]

### extracting year, day, month from EnrollmentDate

In [57]:
df["Enrolment Day"] = df["EnrollmentDate"].dt.day
df["Enrolment Month"] = df["EnrollmentDate"].dt.month
df["Enrolment Year"] = df["EnrollmentDate"].dt.year

df

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks,Enrolment Day,Enrolment Month,Enrolment Year
0,PH0001,Alif Rahman,Completed,2024-09-01,2024-12-23,Ms. Salma,Khulna,300,1,9,2024
1,PH0002,Fatima Akhter,Completed,2024-08-11,2024-11-07,Mr. Karim,Dhaka,271,11,8,2024
2,PH0003,Imran Hossain,Completed,2024-05-08,2024-08-08,Ms. Salma,Dhaka,269,8,5,2024
3,PH0004,Jannatul Ferdous,Completed,2024-07-05,2024-09-23,Mr. Karim,Khulna,270,5,7,2024
4,PH0005,Kamal Uddin,Completed,2024-02-01,2024-04-17,Mr. David,Sylhet,254,1,2,2024
5,PH0006,Laila Begum,Completed,2024-09-07,2024-12-31,Mr. David,Khulna,272,7,9,2024
6,PH0007,Mahmudul Hasan,Completed,2024-06-07,2024-07-20,Mr. David,Chattogram,249,7,6,2024
7,PH0008,Nadia Islam,Completed,2024-03-22,2024-05-01,Ms. Salma,Khulna,246,22,3,2024
8,PH0009,Omar Faruq,Completed,2024-02-12,2024-06-08,Mr. Karim,Dhaka,291,12,2,2024
9,PH0010,Priya Sharma,Completed,2024-06-19,2024-08-19,Mr. David,Dhaka,286,19,6,2024
10,PH0011,Rahim Sheikh,Completed,2024-03-14,2024-06-11,Mr. Karim,Sylhet,283,14,3,2024
11,PH0012,Sadia Chowdhury,Completed,2024-08-04,2024-10-25,Mr. Karim,Sylhet,266,4,8,2024
12,PH0013,Tanvir Ahmed,Completed,2024-06-07,2024-08-03,Mr. David,Dhaka,248,7,6,2024
13,PH0014,Urmi Akter,Completed,2024-01-04,2024-03-23,Mr. David,Sylhet,285,4,1,2024
14,PH0015,Wahiduzzaman,Completed,2024-02-22,2024-05-16,Mr. David,Rajshahi,291,22,2,2024
15,PH0016,Ziaur Rahman,Completed,2024-03-23,2024-06-21,Ms. Salma,Rajshahi,234,23,3,2024
16,PH0017,Afsana Mimi,Completed,2024-01-18,2024-03-16,Mr. David,Khulna,236,18,1,2024
17,PH0018,Babul Ahmed,Completed,2024-06-23,2024-09-20,Mr. David,Dhaka,278,23,6,2024
18,PH0019,Faria Rahman,Completed,2024-04-19,2024-08-17,Mr. Karim,Sylhet,277,19,4,2024
19,PH0020,Tariq Hasan,Completed,2024-07-21,2024-10-11,Mr. Karim,Khulna,253,21,7,2024

In [58]:
df["Duration Required"] = df["FinishedDate"] - df["EnrollmentDate"]
df

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks,Enrolment Day,Enrolment Month,Enrolment Year,Duration Required
0,PH0001,Alif Rahman,Completed,2024-09-01,2024-12-23,Ms. Salma,Khulna,300,1,9,2024,113 days
1,PH0002,Fatima Akhter,Completed,2024-08-11,2024-11-07,Mr. Karim,Dhaka,271,11,8,2024,88 days
2,PH0003,Imran Hossain,Completed,2024-05-08,2024-08-08,Ms. Salma,Dhaka,269,8,5,2024,92 days
3,PH0004,Jannatul Ferdous,Completed,2024-07-05,2024-09-23,Mr. Karim,Khulna,270,5,7,2024,80 days
4,PH0005,Kamal Uddin,Completed,2024-02-01,2024-04-17,Mr. David,Sylhet,254,1,2,2024,76 days
5,PH0006,Laila Begum,Completed,2024-09-07,2024-12-31,Mr. David,Khulna,272,7,9,2024,115 days
6,PH0007,Mahmudul Hasan,Completed,2024-06-07,2024-07-20,Mr. David,Chattogram,249,7,6,2024,43 days
7,PH0008,Nadia Islam,Completed,2024-03-22,2024-05-01,Ms. Salma,Khulna,246,22,3,2024,40 days
8,PH0009,Omar Faruq,Completed,2024-02-12,2024-06-08,Mr. Karim,Dhaka,291,12,2,2024,117 days
9,PH0010,Priya Sharma,Completed,2024-06-19,2024-08-19,Mr. David,Dhaka,286,19,6,2024,61 days
10,PH0011,Rahim Sheikh,Completed,2024-03-14,2024-06-11,Mr. Karim,Sylhet,283,14,3,2024,89 days
11,PH0012,Sadia Chowdhury,Completed,2024-08-04,2024-10-25,Mr. Karim,Sylhet,266,4,8,2024,82 days
12,PH0013,Tanvir Ahmed,Completed,2024-06-07,2024-08-03,Mr. David,Dhaka,248,7,6,2024,57 days
13,PH0014,Urmi Akter,Completed,2024-01-04,2024-03-23,Mr. David,Sylhet,285,4,1,2024,79 days
14,PH0015,Wahiduzzaman,Completed,2024-02-22,2024-05-16,Mr. David,Rajshahi,291,22,2,2024,84 days
15,PH0016,Ziaur Rahman,Completed,2024-03-23,2024-06-21,Ms. Salma,Rajshahi,234,23,3,2024,90 days
16,PH0017,Afsana Mimi,Completed,2024-01-18,2024-03-16,Mr. David,Khulna,236,18,1,2024,58 days
17,PH0018,Babul Ahmed,Completed,2024-06-23,2024-09-20,Mr. David,Dhaka,278,23,6,2024,89 days
18,PH0019,Faria Rahman,Completed,2024-04-19,2024-08-17,Mr. Karim,Sylhet,277,19,4,2024,120 days
19,PH0020,Tariq Hasan,Completed,2024-07-21,2024-10-11,Mr. Karim,Khulna,253,21,7,2024,82 days

## Groupby

In [59]:
df.drop(columns=["StudentID", "FullName", "CompletionStatus", "EnrollmentDate", "FinishedDate"], inplace=True)

In [61]:
g = df.groupby("Instructor")

In [62]:
g.max()

,Location,Total Marks,Enrolment Day,Enrolment Month,Enrolment Year,Duration Required
Instructor,,,,,,
Mr. David,Sylhet,291,23,9,2024,115 days
Mr. Karim,Sylhet,291,21,8,2024,120 days
Ms. Salma,Rajshahi,300,23,9,2024,113 days

In [63]:
g.min()

,Location,Total Marks,Enrolment Day,Enrolment Month,Enrolment Year,Duration Required
Instructor,,,,,,
Mr. David,Chattogram,236,1,1,2024,43 days
Mr. Karim,Dhaka,253,4,2,2024,80 days
Ms. Salma,Dhaka,234,1,3,2024,40 days

In [64]:
g.first()
# first student from every group

,Location,Total Marks,Enrolment Day,Enrolment Month,Enrolment Year,Duration Required
Instructor,,,,,,
Mr. David,Sylhet,254,1,2,2024,76 days
Mr. Karim,Dhaka,271,11,8,2024,88 days
Ms. Salma,Khulna,300,1,9,2024,113 days

In [65]:
g.last()

,Location,Total Marks,Enrolment Day,Enrolment Month,Enrolment Year,Duration Required
Instructor,,,,,,
Mr. David,Dhaka,278,23,6,2024,89 days
Mr. Karim,Khulna,253,21,7,2024,82 days
Ms. Salma,Rajshahi,234,23,3,2024,90 days