# String

In [1]:
str = "hello,hello,"

## type()

In [ ]:
print(type(str))

:

## find()

In [ ]:
print(str.find("hello"))

:

In [ ]:
print(str.rfind("hello"))

:

## capitalize()

In [ ]:
print(str.capitalize())

:

## upper()

In [ ]:
print(str.upper())

:

## lower()

In [ ]:
print(str.lower())

:

## count()

In [ ]:
print(str.count("hello"))

:

## in

In [ ]:
print("hello" in str)

:

## endswith()

In [ ]:
print(str.endswith("."))

:

## replace()

In [ ]:
print(str.replace("hello", "jello"))

:

## len()

In [ ]:
print(len(str))

:

## split()

In [ ]:
print(str.split(","))

:

In [ ]:
name = ["mashrur", "safir", "shabab"]

:

## join()

In [ ]:
print(" ".join(name))

:

## f-string (formatted string literal)

In [ ]:
model_accuracy = 0.8357390327854
print(f"{model_accuracy:.2%}")

:

In [ ]:
_name = "Mashrur Safir Shabab"
research = "QML"
print(f"This is {_name}. My research intereset or domain lies in {research}")

:

# List

In [ ]:
num = [1, 0, 2, 9, 3, 8, 4, 7, 5, 6]

:

## append()

In [ ]:
num.append(10)
print(num)

:

## insert()

In [ ]:
num.insert(len(num), 11)
print(num)

:

## deleting element

### pop()

In [ ]:
num.pop()

:

### remove()

In [ ]:
num.remove(0)
print(num)

:

## sort()

### In ascending order

In [ ]:
num.sort()
print(num)

:

### In descending order

In [ ]:
num.sort(reverse=True)
print(num)

:

## reverse()

In [ ]:
num.reverse()
print(num)

:

## List as stack

In [ ]:
stack = []

:

### stack push

In [ ]:
stack.append(1)
print(stack)

stack.append(2)
print(stack)

stack.append(3)
print(stack)

:

### stack pop

In [ ]:
print(f"popped - {stack.pop()}")
print(f"top - {stack[-1]}\n")

print(f"popped - {stack.pop()}")
print(f"top - {stack[-1]}\n")

print(f"popped - {stack.pop()}")
# print(f"top - {stack[-1]}\n")

:

## List as Queue

### Queue push

In [ ]:
queue = []

:

In [ ]:
queue.append(1)
print(queue)

queue.append(2)
print(queue)

queue.append(3)
print(queue)

:

### Queue pop

In [ ]:
print(f"popped - {queue.pop(0)}")
print(f"top - {queue[0]} \n")

print(f"popped - {queue.pop(0)}")
print(f"top - {queue[0]} \n")

print(f"popped - {queue.pop(0)}")
# print(f"top element - {queue[0]} \n")

:

## List Comprehension

list = [expression loop condition]

In [ ]:
even = [i for i in range(101) if i % 2 == 0]
print(even)

:

In [ ]:
fruits = ["apple", "orange", "watermellon"]
upperFruits = [fruit.upper() for fruit in fruits]
print(upperFruits)

:

# Tuple

ordered, immutable

In [ ]:
a = (10,)
print(type(a), a, "\n")

b = tuple([1, 2, 3, 4, 5])
print(type(b), b, "\n")

:

In [ ]:
tup = (1, 2, 3, 3.5, True, "tuple")
print(type(tup), tup)

:

## count()

In [ ]:
tup.count(True)

:

## index()

In [ ]:
tup.index(1)

:

# Set

stores unique elements, unordered, mutable

In [ ]:
Set = set()
print(type(Set), set)

:

In [ ]:
_set = {1, 2.5, "set", True}
print(type(_set), _set)

:

## add()

In [ ]:
_set.add(False)
print(_set)

:

## pop()

In [ ]:
_set.pop()

:

## remove()

In [ ]:
_set.remove(1)
print(_set)

:

In [ ]:
aSet = {1, 2, 3}
bSet = {2, 3, 4}

:

## union()

In [ ]:
aSet.union(bSet)

:

## intersection

In [ ]:
aSet.intersection(bSet)

:

## isdisjoint()

In [ ]:
aSet.isdisjoint(b)

:

## issubset()

In [ ]:
cSet = {1, 2}
dSet = {1, 2, 3, 4}

cSet.issubset(dSet)

:

# Dictionary

mutable, unordered

In [ ]:
dictionary = {}
print(type(dictionary), dictionary)

:

In [ ]:
dic = {"name" : "Safir",
    0 : "salary",
    1.0: "season",
    "Research Domains" : ["AI/ML", "QC", True, False, 0, 1.5],
    "isEmployed" : False,
    "edu" : "BracU",
    "edu" : {
        "uni" : "BracU",
        "school" : "SHES"
    },
    True : (1, 2, 3, 3.5, True, "tuple"),
    "set" : {1, 2.5, "set", True}}

print(type(dic), dic)

:

## get()

In [ ]:
dic.get("edu", 0)

:

## update()

In [ ]:
dic.update({"ai/ml" : ["NLP", "CV"]})
dic

:

## del

In [ ]:
del dic["ai/ml"]
dic

:

## copy()

In [ ]:
dic2 = dic.copy()
dic2

:

Key has to be immutable <br>
value can be anything

In [ ]:
dic3 = {[1, 2, 3] : "a"}

:

In [ ]:
dic3 = {(1, 2, 3) : "a"}
dic3

:

## keys()
## values()

In [ ]:
dic.keys()

:

In [ ]:
dic.values()

:

## items()

In [ ]:
for key, value in dic.items():
    print(f"{key} - {value}")

:

## Dictionary comprihension

In [ ]:
coordinates = [(10.5, 1), (2.5, 8), (77, 45)]
locations = ["Khulna", "Dhaka", "Chittagong"]

exactLocation = {coor : loc for coor, loc in zip(coordinates, locations)}
print(exactLocation)

:

# Functions

## Keyword argument

In [ ]:
def sum (a, b, c = 30):
    print(a, b, c)
    return a + b + c

output = sum(b = 10, a = 20) + 10
print(output)

:

## Variable Length Argument

In [ ]:
def sum (*args):
    print(args)
    for i in args:
        print(i)

sum(1, 2, 3)

:

## Keyword Arguments

In [ ]:
def info (**kwargs):
    print(kwargs)
    for key, value in kwargs.items():
        print(f"{key} : {value}")

info(a = 10, b = 20)

:

## Value unpacking

In [ ]:
def a():
    return 1, 2

print(type(a()), a())

x, y = a()
print(x, y)

:

In [ ]:
def b():
    a = [1, 2, 3]
    b = [1, 2, 3]
    return a, b

print(type(b()), b())

:

In [ ]:
def c():
    return {1, 2, 3}

print(type(c()), c())

:

## Iterator

In [ ]:
sIterator = {1, 2, 3}
s_iterator = iter(sIterator)
print(type(s_iterator))
print(next(s_iterator))
print(next(s_iterator))
print(next(s_iterator))
print(next(s_iterator))

:

## Generator

In [ ]:
listGen = [i for i in range(100)]

def data_loader(chunk_size, lst):
    for i in range(0, len(lst), chunk_size):
        yield lst[i:i+chunk_size]

data = data_loader(5, listGen) 
print(type(data))
print(next(data))
print(next(data))
print(next(data))
print(next(data))

:

## Lambda Function

In [ ]:
isEven = lambda x : x % 2 == 0
print(isEven(2))

:

## map()

In [ ]:
name = "mashrur safir shabab"
strMap = list(map(str.upper, name))
print(strMap)

name2 = " ".join(strMap)
print(name2)

:

In [ ]:
lstMap = [1, 2, 3]

lstMap2 = list(map(lambda i : i**2 if i % 2 == 0 else i/2, lstMap))
print(lstMap2)

:

## filter()

In [ ]:
dataFilter = [0, None, 1, None, " ", None, [], None, {}, None, (), None, True, None, False]
cleaned_data = list(filter(None, dataFilter))
print(cleaned_data)

:

In [ ]:
numFilter = [i for i in range(100)]
above50 = list(filter(lambda x : x > 50, numFilter))
print(above50)

:

In [ ]:
even = list(filter(lambda x : x % 2 == 0, numFilter))
print(even)

:

In [ ]:
name = "mashrur safir shabab"
vowel = list(filter(lambda x : x in "aeiou", name))
print(vowel)

:

In [ ]:
fruits = ["apple", "orange", "pineapple"]
filtering = list(filter(lambda x : len(x) > 6, fruits))
print(filtering)

:

## reduce()

In [ ]:
from functools import reduce
listReduce = [1, 2, 3, 4, 5]
sum = reduce(lambda x, y : x + y, listReduce)
print(sum)

:

In [ ]:
maxVal = reduce(lambda x, y : x if x > y else y, listReduce)
print(maxVal)

:

# File I/O

In [ ]:
file = open("file.txt", "r")

:

## read()

In [ ]:
content1 = file.read()
print(content1)

:

## readlines()

In [ ]:
content2 = file.readlines()
print(content2)

:

### using map()

In [ ]:
content3 = list(map(str.strip, file))
print(content3)

:

### using filter()

In [ ]:
content4 = list(filter(lambda x : len(x) > 1, file))
print(content4)

:

In [ ]:
print(file.closed)

file.close()

print(file.closed)

:

## with (best practice)

In [ ]:
with open("file.txt", "r") as file:
    content = file.readlines()
    print(content)

print(file.closed)

:

In [ ]:
with open("file.txt", "r") as file:
    for line in file:
        print(line)

:

In [ ]:
with open("file.txt", "r") as file:
    for line in file:
        print(line, end = "")

:

In [ ]:
with open("file.txt", "r") as file:
    for line in file:
        l = line.strip()
        print(l)

:

## write()

overwrite

In [ ]:
with open("test.txt", "w") as file:
    file.write("hey!\n")
    file.write("I am shabab")

:

append

In [ ]:
with open("file.txt", "a") as file:
    file.write("What we know is a drop in the ocean\n")

:

## writelines()

In [ ]:
txt = ["hello\n", "hi\n", "bye\n"]
with open("file.txt", "a") as file:
    file.writelines(txt)

:

## File Pointer

### tell()
### seek()

In [ ]:
with open("helloWorld.txt", "r") as file:
    print(file.tell())
    print(file.seek(6))
    print(file.tell())
    print(file.read())
    print(file.tell())
    print(file.seek(0))
    print(file.read())

:

exercise

In [ ]:
from functools import reduce

with open("file.txt", "r") as file:
    
    # Counting number of lines
    countLines = file.readlines()
    print(countLines)
    l = len(countLines)
    print(f"Total number of lines: {l}\n")

    # Counting number of words
    countWords = list(map(lambda x : len(x.split()), countLines))
    print(countWords)
    countWords = reduce(lambda x, y : x + y, countWords)
    print(f"Total number of words: {countWords}\n")

    # Counting number of characters
    countChars = list(map(str.strip, countLines))
    print(countChars)
    countChars = list(map(lambda x : x.replace(" ", ""), countChars))
    print(countChars)
    countChars = list(map(lambda x : len(x), countChars))
    print(countChars)
    countChars = reduce(lambda x, y : x + y, countChars)
    print(f"Total number of characters {countChars}")

    # saving all the counts in file.txt
    with open("file.txt", "a") as file:
        file.write(f"Total Number of lines: {l}\n")
        file.write(f"Total number of words: {countWords}\n")
        file.write(f"Total number of characters: {countChars}\n")

:

## w+ a+ r+

In [ ]:
with open("file.txt", "a+") as file:
    file.write("Hello World!")
    print(file.tell())
    print(file.read())
    print(file.seek(0))
    print(file.tell())
    print(file.read())

:

# Exception Handling

In [ ]:
n = int(input())

try:
    a = 10/n
    # a = x
except ZeroDivisionError as divErr:
    print(divErr)
except Exception as e:
    print(e)
else:
    print("No exception raised")
finally:
    print("User input taken")


print("Hello there!")

:

# OOP

## Classes and Objects

In [ ]:
class Phone:
    # default attribute
    category = "electronics"

apple = Phone()
mtotorolla = Phone()
blueberry = Phone()

print(f"apple - {apple.category}")
print(f"mtotorolla - {mtotorolla.category}")
print(f"blueberry - {blueberry.category}")
print()
# changing the default category of apple
apple.category = "ultra electronics"
print(f"apple - {apple.category}")

:

## Constructor

In [ ]:
class Dog:
    # constructor
    def __init__(self):
        print("function got called")

dog1 = Dog()    # constructor gets called after an object is created
dog1.name = "tom"
print(dog1.name)

:

In [ ]:
class Phone:
    # default class attribute
    category = "electronics"

    # constructor
    def __init__(self, model, battery, camera, battery_percentage = 100):
        #assigning instance attribue
        self.model = model
        self.battery = battery
        self.camera = camera
        self.battery_percentage = battery_percentage

apple = Phone("I17", 3000, 30)

print(f"default category - {apple.category}")
print(f"model - {apple.model}")
print(f"battery - {apple.battery}")
print(f"camera - {apple.camera}")
print(f"battery percentage - {apple.battery_percentage}")

:

### dir()
lists all methods and attributes of the class object

In [ ]:
dir(apple)

:

## Methods

In [ ]:
# base / parent class
class Phone:
    # class attribute
    category = "electronics"

    # constructor
    def __init__(self, model, battery, camera, battery_percentage = 100):
        # instance attribues
        self.model = model
        self.battery = battery
        self.camera = camera
        self.battery_percentage = battery_percentage

    # instance methods can access both class and instance attribute
    # instance method
    def photoCapture(self, capture):
        if self.battery_percentage < 0:
            print("No charge")
        self.battery_percentage -= capture
        print(f"Phote captured in {self.model}")

    # instance method
    def charge(self, hour):
        print(f"charge duration {hour} hour(s)")

    @classmethod
    def info(self):
        # class methods can only access class attribues
        print(self.category)

apple = Phone("apple", 3000, 30)
samsung = Phone("S7", 40000, 40)
apple.charge(2)
apple.photoCapture(10)
print(f"apple battery percentage - {apple.battery_percentage}")
print(f"samsung battery percentage - {samsung.battery_percentage}")
apple.info()

:

## Inheritence

In [ ]:
# derived / child class
class SmartPhone(Phone):
    def __init__(self, model, battery, camera, processor):
        super().__init__(model, battery, camera)
        self.processor = processor

    def charge(self, hours):
        print("fast charging in progress")
        super().charge(hours)

nothing = SmartPhone("nothing", 1000, 10, "SnapDragon")
print(f"model - {nothing.model}")
print(f"battery - {nothing.battery}")
print(f"battery - {nothing.battery}")
print(f"camera - {nothing.camera}")
print(f"processor - {nothing.processor}")
print(f"battery percentage - {nothing.battery_percentage}")

nothing.photoCapture(30)
print(f"battery percentage after photo capture - {nothing.battery_percentage}")

nothing.charge(10)

:

### Multiple Inheritence

In [ ]:
class CoolingMechanism:
    def __init__(self, method):
        self.method = method

    def coolingOn(self):
        print(f"The system is being cooled by {self.method}")

:

In [ ]:
class SmartPhone_CoolingMechanism(SmartPhone, CoolingMechanism):
    def __init__(self, model, battery, camera, processor, method):
        SmartPhone.__init__(self, model, battery, camera, processor)
        CoolingMechanism.__init__(self, method)

xiaomi = SmartPhone_CoolingMechanism("xiaomi", 1000, 10, "SnapDragon", "Nitro")
print(f"model - {xiaomi.model}")
print(f"battery - {xiaomi.model}")
print(f"camera - {xiaomi.camera}")
print(f"processor - {xiaomi.processor}")
print(f"battery - {xiaomi.battery_percentage}")
xiaomi.photoCapture(10)
print(f"battery after photo capture - {xiaomi.battery_percentage}")
xiaomi.charge(10)
xiaomi.coolingOn()

:

## Polymorphism

In [ ]:
class Camera:
    def __init__(self, name):
        self.name = name

    def capture(self):
        print("a photo is captured")

class Smart(Camera):
    def __init__(self, name, resolution):
        super().__init__(name)
        self.resolution = resolution

    # method overriding
    def capture(self):
        print(f"A photo is being captured by a {self.name}")

class DSLR(Camera):
    def __init__(self, name, resolution):
        super().__init__(name)
        self.resolution = resolution

    # method overriding
    def capture(self):
        print(f"A photo is being captured by a {self.name}")

class Drone(Camera):
    def __init__(self, name, resolution):
        super().__init__(name)
        self.resolution = resolution

    # method overriding
    def capture(self):
        print(f"A photo is being captured by a {self.name}")


smart = Smart("smart_phone", 10)
dslr = DSLR("DSLR", 10)
drone = Drone("Drone", 10)

smart.capture()
dslr.capture()
drone.capture()

:

## Encapsulation

In [ ]:
class Mobile:
    def __init__(self, name, model, imei):
        self.name = name
        self.model = model
        self.__imei = imei    # private

    def charge(self):
        print("Phone is charging")

iphone = Mobile("iphone", 17, 102030)

print(f"Default IMEI: {iphone.__imei}")
iphone.imei = "1x1x1x"
print(f"Updated IMEI: {iphone.__imei}")

:

In [ ]:
class Mobile:
    def __init__(self, name, model, imei):
        self.name = name
        self.model = model
        self.__imei = imei    # private

    def getter(self):
        return self.__imei

iphone = Mobile("iphone", 17, 102030)
print(f"Default IMEI: {iphone.getter()}")
iphone.__imei = "1x2x3x"
print(f"Changed IMEI: {iphone.getter()}")
# imei didn't change and now can only be accessed by getter method

:

In [ ]:
class Mobile:
    def __init__(self, name, model, imei):
        self.__imei = imei    # private

    def getter(self):
        return self.__imei
    
    def setter(self, imei):
        self.__imei = imei

iphone = Mobile("iphone", 17, 102030)
print(f"Default IMEI: {iphone.getter()}")
iphone.setter("1x2x3x")
print(f"Changed IMEI: {iphone.getter()}")

:

## Abstraction

In [ ]:
from ABC import abc, abstractmethod

class Telephone(ABC):

    @abstractmethod
    def makeCalls(self):
        pass

    @abstractmethod
    def capturePhoto(self):
        pass


class iphone(Telephone):

    def makeCalls(self):
        print("Make call")

phone = iphone()
phone.makeCalls()

:

# ndarray

In [151]:
import numpy as np

:

## ndarray declaration

### 1d array

In [152]:
arr1d = np.array([1, 2, 3, 4, 5])
print(type(arr1d), arr1d)
print(arr1d.ndim)
print(arr1d.shape)
print(arr1d.dtype)
print(arr1d.size)

<class 'numpy.ndarray'> [1 2 3 4 5]
1
(5,)
int64
5

:

### 2d array

In [153]:
arr2d = np.array([[1, 2, 3],
                 [4, 5, 6]])
print(arr2d.ndim)
print(arr2d.shape)
print(arr2d.dtype)
print(arr2d.size)

2
(2, 3)
int64
6

:

### 3d array

In [154]:
arr3d = np.array([[[1, 2, 3],
                  [4, 5, 6]],
                  [[7, 8, 9],
                   [10, 11, 12]]])
print(arr3d.ndim)
print(arr3d.shape)
print(arr3d.dtype)
print(arr3d.size)

3
(2, 2, 3)
int64
12

:

## data type

### upcasting to float

In [155]:
floatArr = np.array([1, 2, 3.5])
print(floatArr.dtype)

float64

:

### upcasting to string

In [156]:
stringArr = np.array([1, 2, "3"])
print(stringArr.dtype)

<U21

:

### selecting a data type for an array

In [157]:
arrInt8 = np.array([1, 2, 3], dtype=np.int8)
print(arrInt8.dtype)

int8

:

### changing data type of an exisitng arr

In [159]:
arrFloat16 = arrInt8.astype(np.float16)
print(arrFloat16.dtype, arrFloat16)

float16 [1. 2. 3.]

:

## nd array creation from existing data

### list

In [160]:
lst = [1, 2, 3.5]
arrLst = np.array(lst)
print(type(arrLst))
print(arrLst.dtype)

<class 'numpy.ndarray'>
float64

:

### tuple

In [161]:
tup = (1, 2, 3)
arrTup = np.array(tup)
print(type(arrTup), arrTup)
print(arrTup.dtype)
print(arrTup.shape)
print(arrTup.ndim)

<class 'numpy.ndarray'> [1 2 3]
int64
(3,)
1

:

### set

In [162]:
_set = {1, 2, 3}    
arrSet = np.array(_set)    # treats the whole set as one single element
print(type(arrSet), arrSet)
print(arrSet.dtype)
print(arrSet.shape)
print(arrSet.ndim)

<class 'numpy.ndarray'> {1, 2, 3}
object
()
0

:

In [163]:
arrSet = np.array(list(_set))    # thus, the set has to be typecasted to a list first
print(type(arrSet), arrSet)
print(arrSet.dtype)
print(arrSet.shape)
print(arrSet.ndim)

<class 'numpy.ndarray'> [1 2 3]
int64
(3,)
1

:

### dictionary

In [164]:
dic = {"a" : 1, "b" : 2, "c" : 3}
items = dic.items()
print(f"items: {items}")

keys = dic.keys()
print(f"keys: {keys}")

values = dic.values()
print(f"values: {values}")

items: dict_items([('a', 1), ('b', 2), ('c', 3)])
keys: dict_keys(['a', 'b', 'c'])
values: dict_values([1, 2, 3])

:

In [165]:
arrKeys = np.array(list(keys))    # treats the list within the tuple as one single element. thus, the tuple has to be typecasted to a list first
print(type(arrKeys), arrKeys)
print(arrKeys.dtype)
print(arrKeys.shape)
print(arrKeys.ndim)

<class 'numpy.ndarray'> ['a' 'b' 'c']
<U1
(3,)
1

:

In [166]:
arrValues = np.array(list(values))    # treats the list within the tuple as one single element. thus, the tuple has to be typecasted to a list first
print(type(arrValues), arrValues)
print(arrValues.dtype)
print(arrValues.shape)
print(arrValues.ndim)

<class 'numpy.ndarray'> [1 2 3]
int64
(3,)
1

:

In [167]:
arrItems = np.array(items)
print(type(arrItems), arrItems)
print(arrItems.dtype)
print(arrItems.shape)
print(arrItems.ndim)

<class 'numpy.ndarray'> dict_items([('a', 1), ('b', 2), ('c', 3)])
object
()
0

:

### creating ndarray from scratch

#### zeros()

In [168]:
arrScratch = np.zeros((2, 3))
print(type(arrScratch), arrScratch)
print(arrScratch.dtype)
print(arrScratch.shape)
print(arrScratch.ndim)
print(arrScratch.size)

<class 'numpy.ndarray'> [[0. 0. 0.]
 [0. 0. 0.]]
float64
(2, 3)
2
6

:

#### zeros_like()
getting the array shape from another array

In [169]:
arrScratch2 = np.zeros_like(arr3d)
print(type(arrScratch), arrScratch)
print(arrScratch.dtype)
print(arrScratch.shape)
print(arrScratch.ndim)
print(arrScratch.size)

<class 'numpy.ndarray'> [[0. 0. 0.]
 [0. 0. 0.]]
float64
(2, 3)
2
6

:

#### ones()

In [170]:
arrOnes = np.ones((2, 2))
print(arrOnes)

[[1. 1.]
 [1. 1.]]

:

#### ones_like()

In [171]:
arrOnes2 = np.ones_like(arrOnes)
print(arrOnes2)

[[1. 1.]
 [1. 1.]]

:

#### empty()
creates array using junk values

In [172]:
arrEmpty = np.empty((2, 2))
print(arrEmpty)

[[1. 1.]
 [1. 1.]]

:

#### empty_like()

In [173]:
arrEmpty2 = np.empty_like(arrEmpty)
print(arrEmpty2)

[[1. 1.]
 [1. 1.]]

:

#### full()
creates array using given value

In [174]:
arrFull = np.full((2, 2),"$")
print(arrFull)

[['$' '$']
 ['$' '$']]

:

In [175]:
arrFull2 = np.full_like(arrFull, np.inf, dtype="float64")
print(arrFull2)

[[inf inf]
 [inf inf]]

:

## creating ndarray using random values

### random.rand()
generates random values between 0 and 1

In [176]:
arrRand = np.random.rand(2, 2)
print(type(arrRand), arrRand)
print(arrRand.dtype)
print(arrRand.shape)
print(arrRand.ndim)
print(arrRand.size)

<class 'numpy.ndarray'> [[0.81550395 0.10355306]
 [0.01591652 0.43452373]]
float64
(2, 2)
2
4

:

### random.randint(starting, ending, shape)
creates random values based on the given range

In [177]:
arrRandint = np.random.randint(1, 100, (5, 5))
print(type(arrRandint), arrRandint)
print(arrRandint.dtype)
print(arrRandint.shape)
print(arrRandint.ndim)
print(arrRandint.size)

<class 'numpy.ndarray'> [[ 2 93 53 58 35]
 [ 8 88 73 96 48]
 [13 96 67 68  4]
 [ 2 37 83 27 99]
 [60 40 76 13 24]]
int64
(5, 5)
2
25

:

### random.uniform(starting, ending, shape)
creates random floating point values based on the given range

In [178]:
arrUniform = np.random.uniform(1, 100, (3, 2))
print(type(arrUniform), arrUniform)
print(arrUniform.dtype)
print(arrUniform.shape)
print(arrUniform.ndim)
print(arrUniform.size)

<class 'numpy.ndarray'> [[44.92284502 31.2185992 ]
 [50.39920972 24.90500458]
 [23.68309585 24.56549638]]
float64
(3, 2)
2
6

:

### random.arange(first, end, step)

In [179]:
arrArange = np.arange(1, 10, 1).reshape(3,3)
print(type(arrArange))
print(arrArange)
print(arrArange.dtype)
print(arrArange.shape)
print(arrArange.ndim)
print(arrArange.size)

<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]
int64
(3, 3)
2
9

:

### linspace(start, end(inclusive), number of points to pick)

In [180]:
arrLinspace = np.linspace(1, 10, 5)
print(type(arrLinspace), arrLinspace)
print(arrLinspace.dtype)
print(arrLinspace.shape)
print(arrLinspace.ndim)
print(arrLinspace.size)

<class 'numpy.ndarray'> [ 1.    3.25  5.5   7.75 10.  ]
float64
(5,)
1
5

:

### logspace(start, end(inclusive), number of points to pick with the given base)

In [181]:
arrLogspace = np.logspace(0, 5, 5)
print(type(arrLogspace))    # outputs values from 10^0 - 10^5 since by default the base is 10
print(arrLogspace)
print(arrLogspace.dtype)
print(arrLogspace.shape)
print(arrLogspace.ndim)
print(arrLogspace.size)

<class 'numpy.ndarray'>
[1.00000000e+00 1.77827941e+01 3.16227766e+02 5.62341325e+03
 1.00000000e+05]
float64
(5,)
1
5

:

In [182]:
arrLogspace2 = np.logspace(0, 5, 5, base = 2)
print(type(arrLogspace2) )   # outputs values from 2^0 - 2^5
print(arrLogspace2)
print(arrLogspace2.dtype)
print(arrLogspace2.shape)
print(arrLogspace2.ndim)
print(arrLogspace2.size)

<class 'numpy.ndarray'>
[ 1.          2.37841423  5.65685425 13.45434264 32.        ]
float64
(5,)
1
5

:

## Creating matrix for linear algebra

### diagonal matrix
diag()

In [183]:
arrDiagonal = np.diag([1, 2])
print(arrDiagonal)

[[1 0]
 [0 2]]

:

### Identity matrix
eye(row, column, k)

In [184]:
arrIdentity = np.eye(3)
print(arrIdentity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

:

In [185]:
arrIdentity2 = np.eye(4, 4, -1)
print(arrIdentity2)

[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]

:

## Indexing and slicing
slicing = arr[start : end : step]

In [186]:
slicing = np.array([[1, 2, 3], [4, 5, 6]])
print(slicing)

[[1 2 3]
 [4 5 6]]

:

first row

In [187]:
print(slicing[0:1,])

[[1 2 3]]

:

second row

In [188]:
print(slicing[1:2,])

[[4 5 6]]

:

first column

In [189]:
firstColumn = slicing[::, 0:1]
print(firstColumn)

[[1]
 [4]]

:

second column

In [190]:
secondColumn = slicing[::, 1:2]
print(secondColumn)

[[2]
 [5]]

:

first two columns

In [191]:
firstTwoColumns = slicing[::, 1:3]
print(firstTwoColumns)

[[2 3]
 [5 6]]

:

## copy()

In [192]:
cpy1 = np.array([1, 2, 3, 4, 5])
print(f"cpy1: {cpy1}")

cpy2 = cpy1[1:4].copy()
print(f"cpy2: {cpy2}")

cpy1: [1 2 3 4 5]
cpy2: [2 3 4]

:

In [193]:
cpy2[1] = 100
print(f"cpy2: {cpy2}")

print(f"cpy1: {cpy1}")

cpy2: [  2 100   4]
cpy1: [1 2 3 4 5]

:

## Advanced indexing
[[index1, index2, ..., index n]]

In [194]:
advIdx = np.array([1, 2, 3, 4, 5])
val = advIdx[[1, 4]]
print(val)

[2 5]

:

[[row, row], [col, col]]

In [195]:
advIdx2 = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
val2 = advIdx2[[0,2], [0, 2]]
print(val2)

[1 9]

:

In [196]:
print(advIdx2[advIdx2 > 5])

[6 7 8 9]

:

In [197]:
print(advIdx2[advIdx2 < 5])

[1 2 3 4]

:

replacing all the values that are greater than 5 with 0

In [198]:
advIdx2[advIdx2 > 5] = 0
print(advIdx2)

[[1 2 3]
 [4 5 0]
 [0 0 0]]

:

## nditer(array)
iterating every element of a ndarray

In [199]:
iter = np.array([[1, 2, 3], 
                [4, 5, 6],
                [7, 8, 9]])

for i in np.nditer(iter):
    print(i)

1
2
3
4
5
6
7
8
9

:

## reshape() and shape

In [200]:
re = np.random.randint(1, 100, size = (10, 5))    # sample - 10, features - 5
print(re)

[[ 3 72 59 95 39]
 [24 25 42  5 86]
 [70 83 97 24 58]
 [63 69 21 70 68]
 [64  7 43 90 66]
 [95 76 89 59 32]
 [61 22 51 72 43]
 [96 80 44 24 11]
 [20 56 45 86 49]
 [88 20 84 76 74]]

:

In [201]:
re2 = re.reshape(5, 10)
print(re2)

[[ 3 72 59 95 39 24 25 42  5 86]
 [70 83 97 24 58 63 69 21 70 68]
 [64  7 43 90 66 95 76 89 59 32]
 [61 22 51 72 43 96 80 44 24 11]
 [20 56 45 86 49 88 20 84 76 74]]

:

## flatten
makes the dimension of ndarray to 1 dimension by combining row wise

In [202]:
rowFlatten = re.flatten()
print(rowFlatten)
print(rowFlatten.ndim)

[ 3 72 59 95 39 24 25 42  5 86 70 83 97 24 58 63 69 21 70 68 64  7 43 90
 66 95 76 89 59 32 61 22 51 72 43 96 80 44 24 11 20 56 45 86 49 88 20 84
 76 74]
1

:

flattening column wise
if "f" is passed as the parameter of order then it would flatten column wise
for row wise the parameter is "c"

In [203]:
columnFlatten = np.ravel(re, order = "f")
print(columnFlatten)

[ 3 24 70 63 64 95 61 96 20 88 72 25 83 69  7 76 22 80 56 20 59 42 97 21
 43 89 51 44 45 84 95  5 24 70 90 59 72 24 86 76 39 86 58 68 66 32 43 11
 49 74]

:

## array concatenation

In [204]:
con1 = np.random.randint(1, 10, size = (2, 3))
print(con1)

[[7 4 7]
 [5 8 4]]

:

In [205]:
con2 = np.random.randint(2, 20, size = (2, 3))
print(con2)

[[ 4  7  6]
 [15 12 19]]

:

### row wise
concatenate((matrix1, matrix2), axis=0)

in order to concatenate, column has to be same for both the arrays

to concatenate row wise, the parameter of axis will be 0

In [206]:
conRow = np.concatenate((con1, con2), axis=0)
print(conRow)

[[ 7  4  7]
 [ 5  8  4]
 [ 4  7  6]
 [15 12 19]]

:

### column wise
concatenate((matrix1, matrix2), axis=1)

in order to concatenate, row has to be same for both the arrays

In [207]:
conCol = np.concatenate((con1, con2), axis=1)
print(conCol)

[[ 7  4  7  4  7  6]
 [ 5  8  4 15 12 19]]

:

## transpose matrix

In [208]:
tran = np.array([[1, 2, 3],
                     [4, 5, 6]])
transpose = tran.T
print(transpose)

[[1 4]
 [2 5]
 [3 6]]

:

## splitting array

#### np.array_split(arr, no. of split)

In [209]:
array = np.random.randint(1, 10, size = (10,))
print(array)
splittedArray = np.array_split(array, 3)
print(splittedArray)

[4 9 5 8 8 6 2 4 2 1]
[array([4, 9, 5, 8]), array([8, 6, 2]), array([4, 2, 1])]

:

#### np.split(array, no. of split)
can only be used on arrays where equal divison can take place

In [210]:
arrSplit = np.random.randint(1, 10, size=(10,))
print(arrSplit)
splittedArray2 = np.split(arrSplit, 5)
print(splittedArray2)

[5 7 5 2 5 9 5 1 1 4]
[array([5, 7]), array([5, 2]), array([5, 9]), array([5, 1]), array([1, 4])]

:

## Arithmetic operator and mathematical functions

In [211]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([1, 2, 3, 4, 5])
print(f"x: {x}")
print(f"y: {y}")

x: [1 2 3 4 5]
y: [1 2 3 4 5]

:

### addition, substraction, multiplication, division, mod

In [212]:
print(f"x + y : {x+y}")

print(f"x - y: {x-y}")

print(f"x * y: {x*y}")

print(f"x / y: {x/y}")

print(f"x % y: {x%y}")

x + y : [ 2  4  6  8 10]
x - y: [0 0 0 0 0]
x * y: [ 1  4  9 16 25]
x / y: [1. 1. 1. 1. 1.]
x % y: [0 0 0 0 0]

:

### trigonometry

In [213]:
sin_x = np.sin(x)
print(f"sin(x): {sin_x}")

cos_x = np.cos(x)
print(f"cos(x): {cos_x}")

tan_x = np.tan(x)
print(f"tan(x): {tan_x}")

sin(x): [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
cos(x): [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
tan(x): [ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501]

:

### radian to degree conversion

In [214]:
deg_conversion = np.rad2deg(x)
print(f"radian to degree conversion of x: {deg_conversion}")

radian to degree conversion of x: [ 57.29577951 114.59155903 171.88733854 229.18311805 286.47889757]

:

### degree to radian conversion

In [215]:
rad_conversion = np.deg2rad(deg_conversion)
print(f"degree to radian conversion: {rad_conversion}")

degree to radian conversion: [1. 2. 3. 4. 5.]

:

### log base 10

In [216]:
log_10 = np.log10(x)
print(f"log base 10 values of x: {log_10}")

log base 10 values of x: [0.         0.30103    0.47712125 0.60205999 0.69897   ]

:

### log base 2

In [217]:
log_2 = np.log2(x)
print(f"log base 2 values of x: {log_2}")

log base 2 values of x: [0.         1.         1.5849625  2.         2.32192809]

:

### square root

In [218]:
sqrt = np.sqrt(x)
print(f"square root of x: {sqrt}")

square root of x: [1.         1.41421356 1.73205081 2.         2.23606798]

:

### sum

In [219]:
sum = np.sum(x)
print(f"sum of x: {sum}")

sum of x: 15

:

### cumulative sum

In [220]:
cumulative = np.cumulative_sum(x)
print(f"cumulative sum of x: {cumulative}")

cumulative sum of x: [ 1  3  6 10 15]

:

## Broadcasting

In [221]:
pow2 = x ** 2
print(f"x**2: {pow2}")

sum2 = x + 2
print(f"x+2: {sum2}")

sub2 = x - 2
print(f"x-2: {sub2}")

mul2 = x * 2
print(f"x*2; {mul2}")

div2 = x / 2
print(f"x/2: {div2}")

mod2 = x % 2
print(f"x%2: {mod2}")

x**2: [ 1  4  9 16 25]
x+2: [3 4 5 6 7]
x-2: [-1  0  1  2  3]
x*2; [ 2  4  6  8 10]
x/2: [0.5 1.  1.5 2.  2.5]
x%2: [1 0 1 0 1]

:

In [222]:
# the row size has to be same for both the arrays in such addition

add1 = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

add2 = np.array([1, 2, 3])

add = add1 + add2
print(add)

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]

:

## Logical Function

In [223]:
greater = x > y
print(greater)

lower = x < y
print(lower)

greater_equal = x >= y
print(greater_equal)

lower_equal = x <= y
print(lower_equal)

equal = x == y
print(equal)

notEql = x != y
print(notEql)

[False False False False False]
[False False False False False]
[ True  True  True  True  True]
[ True  True  True  True  True]
[ True  True  True  True  True]
[False False False False False]

:

### all()
finds if all the elements within the array is true

In [224]:
print(np.all(greater_equal))

True

:

In [225]:
print(np.all(greater))

False

:

### any()
finds if any of the element within the array is true

In [226]:
print(np.any(greater))

False

:

In [227]:
print(np.any(greater_equal))

True

:

## sorting

In [228]:
unsorted = np.array([1, 0, 2, 9, 3, 8, 4, 7, 5, 6])

:

### inplace sorting

In [229]:
sortedInplace = unsorted.copy()
print(f"before sorting: {sortedInplace}")
sortedInplace.sort()
print(f"after sorting is applied: {sortedInplace}")

before sorting: [1 0 2 9 3 8 4 7 5 6]
after sorting is applied: [0 1 2 3 4 5 6 7 8 9]

:

### copy sorting

In [230]:
print(f"original array: {unsorted}")
sortedCopy = np.sort(unsorted)
print(f"applying copy sorting: {sortedCopy}")
print(f"original array: {unsorted}")

original array: [1 0 2 9 3 8 4 7 5 6]
applying copy sorting: [0 1 2 3 4 5 6 7 8 9]
original array: [1 0 2 9 3 8 4 7 5 6]

:

### 2d matrix

In [231]:
twoD = np.array([[8, 2, 4],
                [5, 7, 9], 
                [3, 6, 1]])

:

#### horizontal sort
axis=1

In [232]:
horizonSort = np.sort(twoD, axis=1)
print(horizonSort)

[[2 4 8]
 [5 7 9]
 [1 3 6]]

:

#### vertical sort
axis=0

In [233]:
verticalSort = np.sort(twoD, axis=0)
print(verticalSort)

[[3 2 1]
 [5 6 4]
 [8 7 9]]

:

## np.where(element to be searched)

will return the index val of the searched element

In [234]:
idx1 = np.where(x == 1)
print(idx1)

(array([0]),)

:

In [235]:
idx2 = np.where(x > 2)
print(idx2)

(array([2, 3, 4]),)

:

In [236]:
idx4 = np.where(twoD > 5)
print(idx4)

(array([0, 1, 1, 2]), array([0, 1, 2, 1]))

:

## np.where(condition, x, y)
if condition is true, keep x otherwise replace with y

will return the new array

In [237]:
idx3 = np.where(x > 2, x, 0)
print(idx3)

[0 0 3 4 5]

:

In [238]:
idx5 = np.where(twoD > 5, twoD, 0)
print(idx5)

[[8 0 0]
 [0 7 9]
 [0 6 0]]

:

## argmax()
returns the index of the max value in an array

In [239]:
print(x)
maxVal = np.argmax(x)
print(maxVal)

[1 2 3 4 5]
4

:

## argmin()
returns the index of the min value in an array

In [240]:
print(x)
minVal = np.argmin(x)
print(minVal)

[1 2 3 4 5]
0

:

## counting in ndarray

In [241]:
count = np.random.randint(1, 100, size=(100,))
print(count)

[15 52 46 33 30 77 13 99 38 47 22 80 41 90 91 55 20 10 57 23 65 57 48 94
 75 93 27 70 61 33 64  9 81 28 96  8 84 70 78 12 82 94 26 68 52 81 97 85
 64 20 62 25 88 35 11 21 87 24 72 86 95 40 25 99 46 10 12 38 21 15 52 21
 26 32 23 45 43 87 45 26 64 95 64 91 97 73 29 56 13 37 55 63 83 24 61 63
 77 14 14 54]

:

In [242]:
val_greaterThan_5 = np.count_nonzero(count > 50)
print(val_greaterThan_5)

52

:

In [243]:
val_equal_2 = np.count_nonzero(count == 20)
print(val_equal_2)

2

:

In [244]:
val_lessThan_50 = np.count_nonzero(count < 50)
print(val_lessThan_50)

48

:

## np.unique()
provides unique values from the given array

In [245]:
uniqueVal = np.unique(count, return_counts=True)
print(uniqueVal)

(array([ 8,  9, 10, 11, 12, 13, 14, 15, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 32, 33, 35, 37, 38, 40, 41, 43, 45, 46, 47, 48, 52, 54, 55,
       56, 57, 61, 62, 63, 64, 65, 68, 70, 72, 73, 75, 77, 78, 80, 81, 82,
       83, 84, 85, 86, 87, 88, 90, 91, 93, 94, 95, 96, 97, 99]), array([1, 1, 2, 1, 2, 2, 2, 2, 2, 3, 1, 2, 2, 2, 3, 1, 1, 1, 1, 1, 2, 1,
       1, 2, 1, 1, 1, 2, 2, 1, 1, 3, 1, 2, 1, 2, 2, 1, 2, 4, 1, 1, 2, 1,
       1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 2, 2, 1, 2, 2]))

:

In [246]:
# value unpacking since it returns an array
uniqueVal, count = np.unique(count, return_counts=True)
print(uniqueVal)
print(count)

[ 8  9 10 11 12 13 14 15 20 21 22 23 24 25 26 27 28 29 30 32 33 35 37 38
 40 41 43 45 46 47 48 52 54 55 56 57 61 62 63 64 65 68 70 72 73 75 77 78
 80 81 82 83 84 85 86 87 88 90 91 93 94 95 96 97 99]
[1 1 2 1 2 2 2 2 2 3 1 2 2 2 3 1 1 1 1 1 2 1 1 2 1 1 1 2 2 1 1 3 1 2 1 2 2
 1 2 4 1 1 2 1 1 1 2 1 1 2 1 1 1 1 1 2 1 1 2 1 2 2 1 2 2]

:

## Statistical Analysis

### Data Load

In [247]:
data = np.genfromtxt("marks.csv", delimiter=",", skip_header=1)
print(data)

[[  1.   2.   3.]
 [  4.   5.   6.]
 [  7.   8.   9.]
 [ 10.  11.  12.]
 [ 13.  14.  15.]
 [ 16.  17.  18.]
 [ 19.  20.  21.]
 [ 22.  23.  24.]
 [ 25.  26.  27.]
 [ 28.  29.  30.]
 [ 31.  32.  34.]
 [ 35.  36.  37.]
 [ 38.  39.  40.]
 [ 41.  42.  43.]
 [ 44.  45.  46.]
 [ 47.  48.  49.]
 [ 50.  51.  52.]
 [ 53.  54.  55.]
 [ 56.  57.  58.]
 [ 59.  60.  61.]
 [ 62.  63.  64.]
 [ 65.  66.  67.]
 [ 68.  69.  70.]
 [ 71.  72.  73.]
 [ 74.  75.  76.]
 [ 77.  78.  79.]
 [ 80.  81.  82.]
 [ 83.  84.  85.]
 [ 86.  87.  88.]
 [ 89.  90.  91.]
 [ 92.  93.  94.]
 [ 95.  96.  97.]
 [ 98.  99. 100.]]

:

### math marks

In [248]:
mat = data[::, :1]
print(mat)

[[ 1.]
 [ 4.]
 [ 7.]
 [10.]
 [13.]
 [16.]
 [19.]
 [22.]
 [25.]
 [28.]
 [31.]
 [35.]
 [38.]
 [41.]
 [44.]
 [47.]
 [50.]
 [53.]
 [56.]
 [59.]
 [62.]
 [65.]
 [68.]
 [71.]
 [74.]
 [77.]
 [80.]
 [83.]
 [86.]
 [89.]
 [92.]
 [95.]
 [98.]]

:

In [249]:
print(mat.T)

[[ 1.  4.  7. 10. 13. 16. 19. 22. 25. 28. 31. 35. 38. 41. 44. 47. 50. 53.
  56. 59. 62. 65. 68. 71. 74. 77. 80. 83. 86. 89. 92. 95. 98.]]

:

### finding max math marks

In [250]:
matMax = np.max(mat)
print(matMax)

98.0

:

### finding min math marks

In [251]:
minMath = np.min(mat)
print(minMath)

1.0

:

### finding average math marks

In [252]:
avgMath = np.mean(mat)
print(avgMath)

49.666666666666664

:

### finding median math marks

In [253]:
medianMath = np.median(mat)
print(medianMath)

50.0

:

### finding standard deviation
the more large standard deviation is, the more scattered the data are

In [254]:
sdMath = np.std(mat)
print(sdMath)

28.95206766747795

:

## correlation coefficient

In [255]:
studyHours = np.array([1, 2, 3, 4, 5])
examScores = np.array([60, 70, 80, 90, 100])
data = np.array([studyHours, 
                 examScores])
print(data)

[[  1   2   3   4   5]
 [ 60  70  80  90 100]]

:

In [256]:
correlation = np.corrcoef(data)
print(correlation)

[[1. 1.]
 [1. 1.]]

:

## Linear Algebra

In [257]:
matrix1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

matrix2 = np.array([[7, 8],
                   [9, 10],
                   [11, 12]])

:

### matrix multiplication

In [258]:
dotProduct = np.dot(matrix1, matrix2)
print(dotProduct)

[[ 58  64]
 [139 154]]

:

### trace matrix
summation of the diagonal elements

In [259]:
trace = np.trace(matrix1)
print(trace)

6

:

### determinent of a matrix

In [260]:
matrix3 = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

det = np.linalg.det(matrix3)
print(det)

0.0

:

### rank of a matrix

In [261]:
rank = np.linalg.matrix_rank(matrix3)
print(rank)

2

:

# Pandas

In [30]:
import pandas as pd

:

## Different file loading

### csv file

In [122]:
df = pd.read_csv("student_data.csv")
print(df, type(df))

   StudentID          FullName  Data Structure Marks  Algorithm Marks  \
0     PH1001       Alif Rahman                  85.0             85.0
1     PH1002     Fatima Akhter                  92.0             92.0
2     PH1003     Imran Hossain                  88.0             88.0
3     PH1004  Jannatul Ferdous                  78.0             78.0
4     PH1005       Kamal Uddin                   NaN              NaN
5     PH1006       Laila Begum                  75.0             75.0
6     PH1007    Mahmudul Hasan                  80.0             80.0
7     PH1008       Nadia Islam                  81.0             81.0
8     PH1009        Omar Faruq                  72.0             72.0
9     PH1010      Priya Sharma                  89.0             89.0
10    PH1011      Rahim Sheikh                   NaN              NaN
11    PH1012   Sadia Chowdhury                  85.0             85.0
12    PH1013      Tanvir Ahmed                  75.0             75.0
13    PH1014        Urmi Akter                   NaN              NaN
14    PH1015      Wahiduzzaman                  86.0             86.0
15    PH1016      Ziaur Rahman                  94.0             94.0
16    PH1017       Afsana Mimi                  90.0             90.0
17    PH1018       Babul Ahmed                  88.0             88.0
18    PH1019      Faria Rahman                   NaN              NaN
19    PH1020        Nasir Khan                  86.0             86.0

    Python Marks CompletionStatus EnrollmentDate Instructor    Location
0           88.0        Completed     2024-01-15  Mr. Karim       Dhaka
1            NaN      In Progress     2024-01-20  Ms. Salma  Chattogram
2           85.0        Completed     2024-02-10  Mr. Karim       Dhaka
3           82.0        Completed     2024-02-12  Ms. Salma      Sylhet
4           95.0      In Progress     2024-03-05  Mr. Karim  Chattogram
5           78.0        Completed     2024-03-08  Ms. Salma    Rajshahi
6            NaN      In Progress     2024-04-01  Mr. Karim       Dhaka
7           85.0        Completed     2024-04-22  Ms. Salma  Chattogram
8           76.0        Completed     2024-05-16  Mr. David       Dhaka
9           88.0        Completed     2024-05-20  Ms. Salma      Sylhet
10          91.0      In Progress     2024-06-11  Mr. Karim      Khulna
11          87.0        Completed     2024-06-14  Ms. Salma  Chattogram
12          79.0        Completed     2024-07-02  Mr. David       Dhaka
13           NaN      Not Started     2024-07-09  Ms. Salma    Rajshahi
14          84.0        Completed     2024-08-18  Mr. Karim       Dhaka
15           NaN      In Progress     2024-08-21  Ms. Salma  Chattogram
16          93.0        Completed     2025-09-01  Mr. Karim       Dhaka
17          85.0        Completed     2025-09-05  Ms. Salma      Sylhet
18           NaN      Not Started     2025-09-15  Mr. David  Chattogram
19          89.0        Completed     2025-10-02  Ms. Salma       Dhaka   <class 'pandas.core.frame.DataFrame'>

:

In [32]:
student_id = df["StudentID"]
print(student_id, type(student_id))

0     PH1001
1     PH1002
2     PH1003
3     PH1004
4     PH1005
5     PH1006
6     PH1007
7     PH1008
8     PH1009
9     PH1010
10    PH1011
11    PH1012
12    PH1013
13    PH1014
14    PH1015
15    PH1016
16    PH1017
17    PH1018
18    PH1019
19    PH1020
Name: StudentID, dtype: object <class 'pandas.core.series.Series'>

:

### excel file

In [33]:
df_xlsx = pd.read_excel('student_marks.xlsx')
print(df_xlsx, type(df_xlsx))

   StudentID          FullName  Data Structure Marks  Algorithm Marks  \
0     PH1001       Alif Rahman                  85.0             85.0
1     PH1002     Fatima Akhter                  92.0             92.0
2     PH1003     Imran Hossain                  88.0             88.0
3     PH1004  Jannatul Ferdous                  78.0             78.0
4     PH1005       Kamal Uddin                   NaN              NaN
5     PH1006       Laila Begum                  75.0             75.0
6     PH1007    Mahmudul Hasan                  80.0             80.0
7     PH1008       Nadia Islam                  81.0             81.0
8     PH1009        Omar Faruq                  72.0             72.0
9     PH1010      Priya Sharma                  89.0             89.0
10    PH1011      Rahim Sheikh                   NaN              NaN
11    PH1012   Sadia Chowdhury                  85.0             85.0
12    PH1013      Tanvir Ahmed                  75.0             75.0
13    PH1014        Urmi Akter                   NaN              NaN
14    PH1015      Wahiduzzaman                  86.0             86.0
15    PH1016      Ziaur Rahman                  94.0             94.0
16    PH1017       Afsana Mimi                  90.0             90.0
17    PH1018       Babul Ahmed                  88.0             88.0
18    PH1019      Faria Rahman                   NaN              NaN
19    PH1020        Nasir Khan                  86.0             86.0

    Python Marks CompletionStatus EnrollmentDate Instructor    Location
0           88.0        Completed     2024-01-15  Mr. Karim       Dhaka
1            NaN      In Progress     2024-01-20  Ms. Salma  Chattogram
2           85.0        Completed     2024-02-10  Mr. Karim       Dhaka
3           82.0        Completed     2024-02-12  Ms. Salma      Sylhet
4           95.0      In Progress     2024-03-05  Mr. Karim  Chattogram
5           78.0        Completed     2024-03-08  Ms. Salma    Rajshahi
6            NaN      In Progress     2024-04-01  Mr. Karim       Dhaka
7           85.0        Completed     2024-04-22  Ms. Salma  Chattogram
8           76.0        Completed     2024-05-16  Mr. David       Dhaka
9           88.0        Completed     2024-05-20  Ms. Salma      Sylhet
10          91.0      In Progress     2024-06-11  Mr. Karim      Khulna
11          87.0        Completed     2024-06-14  Ms. Salma  Chattogram
12          79.0        Completed     2024-07-02  Mr. David       Dhaka
13           NaN      Not Started     2024-07-09  Ms. Salma    Rajshahi
14          84.0        Completed     2024-08-18  Mr. Karim       Dhaka
15           NaN      In Progress     2024-08-21  Ms. Salma  Chattogram
16          93.0        Completed     2025-09-01  Mr. Karim       Dhaka
17          85.0        Completed     2025-09-05  Ms. Salma      Sylhet
18           NaN      Not Started     2025-09-15  Mr. David  Chattogram
19          89.0        Completed     2025-10-02  Ms. Salma       Dhaka   <class 'pandas.core.frame.DataFrame'>

:

In [34]:
import pyarrow

:

### parquet file

In [35]:
df_parquet = pd.read_parquet('student_marks.parquet')
print(df_parquet, type(df_parquet))

   StudentID          FullName  Data Structure Marks  Algorithm Marks  \
0     PH1001       Alif Rahman                  85.0             85.0
1     PH1002     Fatima Akhter                  92.0             92.0
2     PH1003     Imran Hossain                  88.0             88.0
3     PH1004  Jannatul Ferdous                  78.0             78.0
4     PH1005       Kamal Uddin                   NaN              NaN
5     PH1006       Laila Begum                  75.0             75.0
6     PH1007    Mahmudul Hasan                  80.0             80.0
7     PH1008       Nadia Islam                  81.0             81.0
8     PH1009        Omar Faruq                  72.0             72.0
9     PH1010      Priya Sharma                  89.0             89.0
10    PH1011      Rahim Sheikh                   NaN              NaN
11    PH1012   Sadia Chowdhury                  85.0             85.0
12    PH1013      Tanvir Ahmed                  75.0             75.0
13    PH1014        Urmi Akter                   NaN              NaN
14    PH1015      Wahiduzzaman                  86.0             86.0
15    PH1016      Ziaur Rahman                  94.0             94.0
16    PH1017       Afsana Mimi                  90.0             90.0
17    PH1018       Babul Ahmed                  88.0             88.0
18    PH1019      Faria Rahman                   NaN              NaN
19    PH1020        Nasir Khan                  86.0             86.0

    Python Marks CompletionStatus EnrollmentDate Instructor    Location
0           88.0        Completed     2024-01-15  Mr. Karim       Dhaka
1            NaN      In Progress     2024-01-20  Ms. Salma  Chattogram
2           85.0        Completed     2024-02-10  Mr. Karim       Dhaka
3           82.0        Completed     2024-02-12  Ms. Salma      Sylhet
4           95.0      In Progress     2024-03-05  Mr. Karim  Chattogram
5           78.0        Completed     2024-03-08  Ms. Salma    Rajshahi
6            NaN      In Progress     2024-04-01  Mr. Karim       Dhaka
7           85.0        Completed     2024-04-22  Ms. Salma  Chattogram
8           76.0        Completed     2024-05-16  Mr. David       Dhaka
9           88.0        Completed     2024-05-20  Ms. Salma      Sylhet
10          91.0      In Progress     2024-06-11  Mr. Karim      Khulna
11          87.0        Completed     2024-06-14  Ms. Salma  Chattogram
12          79.0        Completed     2024-07-02  Mr. David       Dhaka
13           NaN      Not Started     2024-07-09  Ms. Salma    Rajshahi
14          84.0        Completed     2024-08-18  Mr. Karim       Dhaka
15           NaN      In Progress     2024-08-21  Ms. Salma  Chattogram
16          93.0        Completed     2025-09-01  Mr. Karim       Dhaka
17          85.0        Completed     2025-09-05  Ms. Salma      Sylhet
18           NaN      Not Started     2025-09-15  Mr. David  Chattogram
19          89.0        Completed     2025-10-02  Ms. Salma       Dhaka   <class 'pandas.core.frame.DataFrame'>

:

### json file

In [36]:
df_json = pd.read_json('student_marks.json')
print(df_json, type(df_json))

  StudentID          FullName  Data Structure Marks  Algorithm Marks  \
0    PH1001       Alif Rahman                    85               85
1    PH1002     Fatima Akhter                    92               92
2    PH1004  Jannatul Ferdous                    78               78

   Python Marks
0            88
1            90
2            82   <class 'pandas.core.frame.DataFrame'>

:

## df

In [37]:
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

:

### head()
shows the first 5 rows of the data frame if no parameter is passed
so by default, the parameter is 5

In [38]:
df.head()

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram

:

In [39]:
df.head(9)

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka

:

### tail()
by default shows the last 5 rows if no parameter is passed

In [40]:
df.tail()

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

:

In [41]:
df.tail(2)

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

:

### columns
attribute of the df class

In [42]:
df.columns

Index(['StudentID', 'FullName', 'Data Structure Marks', 'Algorithm Marks',
       'Python Marks', 'CompletionStatus', 'EnrollmentDate', 'Instructor',
       'Location'],
      dtype='object')

:

In [43]:
col = list(df.columns)
print(col, type(col))

['StudentID', 'FullName', 'Data Structure Marks', 'Algorithm Marks', 'Python Marks', 'CompletionStatus', 'EnrollmentDate', 'Instructor', 'Location'] <class 'list'>

:

In [46]:
col2 = np.array(df.columns)
print(col2, col2.dtype)

['StudentID' 'FullName' 'Data Structure Marks' 'Algorithm Marks'
 'Python Marks' 'CompletionStatus' 'EnrollmentDate' 'Instructor'
 'Location'] object

:

### index
this is the attribute of the df class which shows the range of the starting to ending_index+1 of the data frame

In [47]:
df.index

RangeIndex(start=0, stop=20, step=1)

:

In [48]:
idx = np.array(df.index)
print(idx, idx.dtype)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] int64

:

### info()
shows info regarding df

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   StudentID             20 non-null     object
 1   FullName              20 non-null     object
 2   Data Structure Marks  16 non-null     float64
 3   Algorithm Marks       16 non-null     float64
 4   Python Marks          15 non-null     float64
 5   CompletionStatus      20 non-null     object
 6   EnrollmentDate        20 non-null     object
 7   Instructor            20 non-null     object
 8   Location              20 non-null     object
dtypes: float64(3), object(6)
memory usage: 1.5+ KB

:

### sample()
by default shows only 1 sample data randomly (if no parameter is passed)

In [50]:
df.sample()

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram

:

In [51]:
df.sample(10)

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram

:

### statistical values

#### describe()

In [52]:
df.describe()

       Data Structure Marks  Algorithm Marks  Python Marks
count             16.000000        16.000000     15.000000
mean              84.000000        84.000000     85.666667
std                6.501282         6.501282      5.394000
min               72.000000        72.000000     76.000000
25%               79.500000        79.500000     83.000000
50%               85.500000        85.500000     85.000000
75%               88.250000        88.250000     88.500000
max               94.000000        94.000000     95.000000

:

## Transforming to series from inbuilt data

### list

In [53]:
l = [10, 20, 30]
l_sr = pd.Series(l, index=["x", "y", "z"])
print(type(l_sr))
l_sr

<class 'pandas.core.series.Series'>

x    10
y    20
z    30
dtype: int64

:

#### accessing by key

In [54]:
print(l_sr["x"])

10

:

#### accessing by index

In [55]:
print(l[0])

10

:

#### accessing by multipe keys

In [56]:
print(l_sr[["x", "z"]])

x    10
z    30
dtype: int64

:

#### accessing via label - loc() and index - iloc()

In [57]:
# loc() only works with the value that is assiged to the index
print(l_sr.loc["x"])

10

:

In [58]:
print(l_sr.loc[["x", "y"]])

x    10
y    20
dtype: int64

:

In [59]:
# iloc() only works with integer values
print(l_sr.iloc[0])

10

:

#### series slicing

##### using values assigned in index

In [60]:
print(l_sr["x":"y"])    # loc()

x    10
y    20
dtype: int64

:

In [61]:
l_sr.loc["x":"y"]

x    10
y    20
dtype: int64

:

##### using index values

In [62]:
l_sr[0:2]    # iloc()

x    10
y    20
dtype: int64

:

In [65]:
l_sr.iloc[0:2]

x    10
y    20
dtype: int64

##### get()

In [63]:
print(l_sr.get("x", 0))

10

:

In [64]:
# 0 is the default value that will be displayed if the index/key is not found
print(l_sr.get("a", 0))

0

:

### dictionary

In [66]:
d = {"a":10, "b":20, "c":30}
d_sr = pd.Series(d)
print(type(d_sr))
d_sr

<class 'pandas.core.series.Series'>

a    10
b    20
c    30
dtype: int64

In [67]:
print(d_sr["a"])

10

## creating data frame from series

In [68]:
name = ["alice", "bob", "carol"]
age = [10, 20, 30]
series1 = pd.Series(name)
series2 = pd.Series(age)
df_s = pd.DataFrame({"name" : series1, "age" : series2})
df_s

    name  age
0  alice   10
1    bob   20
2  carol   30

## Transforming to data frame from inbuilt datas

### list

In [69]:
lst = [["Alice", 25],
       ["Bob", 30],
       ["Charlie", 28]]

In [70]:
list_df = pd.DataFrame(lst, columns=["Name", "Age"],index=[1, 2, 3])
print(list_df)
print()
print(type(list_df))

      Name  Age
1    Alice   25
2      Bob   30
3  Charlie   28

<class 'pandas.core.frame.DataFrame'>

Name    object
Age      int64
dtype: object

In [71]:
list_df

      Name  Age
1    Alice   25
2      Bob   30
3  Charlie   28

### tuple

In [72]:
tup = (("Alice", 25),
       ("Bob", 30),
       ("Charlie", 28))

In [73]:
tup_df = pd.DataFrame(tup, columns=["Name", "Age"], index=[1,2,3])
print(tup_df)
print()
print(type(tup_df))
print()
print(tup_df.dtypes)

      Name  Age
1    Alice   25
2      Bob   30
3  Charlie   28

<class 'pandas.core.frame.DataFrame'>

Name    object
Age      int64
dtype: object

In [74]:
tup_df

      Name  Age
1    Alice   25
2      Bob   30
3  Charlie   28

### dictionary

In [75]:
dic = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 28],
}

In [76]:
dic_df = pd.DataFrame(dic)
print(dic_df)
print()
print(type(dic_df))
print()
print(dic_df.dtypes)

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   28

<class 'pandas.core.frame.DataFrame'>

Name    object
Age      int64
dtype: object

In [77]:
dic_df

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   28

### dictionary within a list

In [78]:
l = [
    {"Name": "Alice", "Age": 25, "City": "New York"},
    {"Name": "Bob", "Age": 30, "City": "New York"},
    {"Name": "Charlie", "Age": 28},
]

In [79]:
l_df = pd.DataFrame(l)
print(l_df)
print()
print(type(l_df))
print()
print(l_df.dtypes)

      Name  Age      City
0    Alice   25  New York
1      Bob   30  New York
2  Charlie   28       NaN

<class 'pandas.core.frame.DataFrame'>

Name    object
Age      int64
City    object
dtype: object

In [80]:
l_df

      Name  Age      City
0    Alice   25  New York
1      Bob   30  New York
2  Charlie   28       NaN

## Accessing values from data frame

### accessing a column
a number of series creates a data frame

In [81]:
full_name = df["FullName"]
print(full_name, type(full_name), full_name.dtype)

0          Alif Rahman
1        Fatima Akhter
2        Imran Hossain
3     Jannatul Ferdous
4          Kamal Uddin
5          Laila Begum
6       Mahmudul Hasan
7          Nadia Islam
8           Omar Faruq
9         Priya Sharma
10        Rahim Sheikh
11     Sadia Chowdhury
12        Tanvir Ahmed
13          Urmi Akter
14        Wahiduzzaman
15        Ziaur Rahman
16         Afsana Mimi
17         Babul Ahmed
18        Faria Rahman
19          Nasir Khan
Name: FullName, dtype: object <class 'pandas.core.series.Series'> object

### loc[row(index), col(features)]
df.loc[ row_start:row_end, col_start:col_end ]

#### single row

In [82]:
df.loc[0]

StudentID                    PH1001
FullName                Alif Rahman
Data Structure Marks           85.0
Algorithm Marks                85.0
Python Marks                   88.0
CompletionStatus          Completed
EnrollmentDate           2024-01-15
Instructor                Mr. Karim
Location                      Dhaka
Name: 0, dtype: object

In [83]:
type(df.loc[0])

pandas.core.series.Series

#### multiple row

##### using list

In [84]:
df.loc[[2, 3, 19]]

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

##### using range

In [85]:
df.loc[3:7]

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram

#### column

##### single

In [86]:
df.loc[:, "Python Marks"]

0     88.0
1      NaN
2     85.0
3     82.0
4     95.0
5     78.0
6      NaN
7     85.0
8     76.0
9     88.0
10    91.0
11    87.0
12    79.0
13     NaN
14    84.0
15     NaN
16    93.0
17    85.0
18     NaN
19    89.0
Name: Python Marks, dtype: float64

##### multiple

In [87]:
df.loc[:, ["Python Marks", "CompletionStatus"]]

    Python Marks CompletionStatus
0           88.0        Completed
1            NaN      In Progress
2           85.0        Completed
3           82.0        Completed
4           95.0      In Progress
5           78.0        Completed
6            NaN      In Progress
7           85.0        Completed
8           76.0        Completed
9           88.0        Completed
10          91.0      In Progress
11          87.0        Completed
12          79.0        Completed
13           NaN      Not Started
14          84.0        Completed
15           NaN      In Progress
16          93.0        Completed
17          85.0        Completed
18           NaN      Not Started
19          89.0        Completed

In [88]:
type(df.loc[:, ["Python Marks", "CompletionStatus"]])
# data frame since it is a collection of series

pandas.core.frame.DataFrame

#### row and column

In [89]:
df.loc[3:7,["Data Structure Marks", "Algorithm Marks", "Python Marks", "CompletionStatus"]]

   Data Structure Marks  Algorithm Marks  Python Marks CompletionStatus
3                  78.0             78.0          82.0        Completed
4                   NaN              NaN          95.0      In Progress
5                  75.0             75.0          78.0        Completed
6                  80.0             80.0           NaN      In Progress
7                  81.0             81.0          85.0        Completed

### iat(row, col)

In [90]:
df.iat[0, 0]    # oth row, oth col
# df.iat[0, 1]    # 0th row, 1st col

'PH1001'

## Changing index

In [91]:
df2 = df.set_index("StudentID")    # if we want to make this change to the original df, then we will have to pass the parameter
df2                                # inplace = True within the set_index method

,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
StudentID,,,,,,,,
PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

### iloc

In [92]:
df2.iloc[3:7, 1:5]

,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus
StudentID,,,,
PH1004,78.0,78.0,82.0,Completed
PH1005,NaN,NaN,95.0,In Progress
PH1006,75.0,75.0,78.0,Completed
PH1007,80.0,80.0,NaN,In Progress

## Renaming columns

In [93]:
df3 = df2.rename(columns={"FullName" : "Full Name"})
df3
# need to pass the parameter inplace = True if we intend to change the original data frame

,Full Name,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
StudentID,,,,,,,,
PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

## Adding columns

In [94]:
df["Salary"] = 0
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Salary
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,0
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,0
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,0
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,0
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,0
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,0
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka,0
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,0
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,0
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,0
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,0
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,0
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,0
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi,0
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,0
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram,0
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,0
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,0
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram,0
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,0

## dropping rows and columns
drop()

In [95]:
df3.drop("PH1001", inplace=True)
df3

,Full Name,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
StudentID,,,,,,,,
PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

In [96]:
df3.drop("Location", axis=1, inplace=True)
df3

,Full Name,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor
StudentID,,,,,,,
PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma
PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim
PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma
PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim
PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma
PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim
PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma
PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David
PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma
PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim
PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma
PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David
PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma
PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim
PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma
PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim
PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma
PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David
PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma

## assigning or changing marks

In [97]:
# df3.loc[0, "Python Marks"] = 90
df3.iloc[0, 3] = 90
# df3.loc[0, "CompletionStatus"] = "Completed"
df3.iloc[0, 4] = "Completed"
df3

,Full Name,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor
StudentID,,,,,,,
PH1002,Fatima Akhter,92.0,92.0,90.0,Completed,2024-01-20,Ms. Salma
PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim
PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma
PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim
PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma
PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim
PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma
PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David
PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma
PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim
PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma
PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David
PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma
PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim
PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma
PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim
PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma
PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David
PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma

In [98]:
# df3.loc[0:3, "Python Marks"] += 1
df3.iloc[0:3, 3] += 1
df3

,Full Name,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor
StudentID,,,,,,,
PH1002,Fatima Akhter,92.0,92.0,91.0,Completed,2024-01-20,Ms. Salma
PH1003,Imran Hossain,88.0,88.0,86.0,Completed,2024-02-10,Mr. Karim
PH1004,Jannatul Ferdous,78.0,78.0,83.0,Completed,2024-02-12,Ms. Salma
PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim
PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma
PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim
PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma
PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David
PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma
PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim
PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma
PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David
PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma
PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim
PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma
PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim
PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma
PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David
PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma

## looping through a data frame

### iterrows()

In [99]:
for i, series in df.iterrows():
    print(f"{i} -----> {series}")
# provides series from each row

0 -----> StudentID                    PH1001
FullName                Alif Rahman
Data Structure Marks           85.0
Algorithm Marks                85.0
Python Marks                   88.0
CompletionStatus          Completed
EnrollmentDate           2024-01-15
Instructor                Mr. Karim
Location                      Dhaka
Salary                            0
Name: 0, dtype: object
1 -----> StudentID                      PH1002
FullName                Fatima Akhter
Data Structure Marks             92.0
Algorithm Marks                  92.0
Python Marks                      NaN
CompletionStatus          In Progress
EnrollmentDate             2024-01-20
Instructor                  Ms. Salma
Location                   Chattogram
Salary                              0
Name: 1, dtype: object
2 -----> StudentID                      PH1003
FullName                Imran Hossain
Data Structure Marks             88.0
Algorithm Marks                  88.0
Python Marks                     85.0
CompletionStatus            Completed
EnrollmentDate             2024-02-10
Instructor                  Mr. Karim
Location                        Dhaka
Salary                              0
Name: 2, dtype: object
3 -----> StudentID                         PH1004
FullName                Jannatul Ferdous
Data Structure Marks                78.0
Algorithm Marks                     78.0
Python Marks                        82.0
CompletionStatus               Completed
EnrollmentDate                2024-02-12
Instructor                     Ms. Salma
Location                          Sylhet
Salary                                 0
Name: 3, dtype: object
4 -----> StudentID                    PH1005
FullName                Kamal Uddin
Data Structure Marks            NaN
Algorithm Marks                 NaN
Python Marks                   95.0
CompletionStatus        In Progress
EnrollmentDate           2024-03-05
Instructor                Mr. Karim
Location                 Chattogram
Salary                            0
Name: 4, dtype: object
5 -----> StudentID                    PH1006
FullName                Laila Begum
Data Structure Marks           75.0
Algorithm Marks                75.0
Python Marks                   78.0
CompletionStatus          Completed
EnrollmentDate           2024-03-08
Instructor                Ms. Salma
Location                   Rajshahi
Salary                            0
Name: 5, dtype: object
6 -----> StudentID                       PH1007
FullName                Mahmudul Hasan
Data Structure Marks              80.0
Algorithm Marks                   80.0
Python Marks                       NaN
CompletionStatus           In Progress
EnrollmentDate              2024-04-01
Instructor                   Mr. Karim
Location                         Dhaka
Salary                               0
Name: 6, dtype: object
7 -----> StudentID                    PH1008
FullName                Nadia Islam
Data Structure Marks           81.0
Algorithm Marks                81.0
Python Marks                   85.0
CompletionStatus          Completed
EnrollmentDate           2024-04-22
Instructor                Ms. Salma
Location                 Chattogram
Salary                            0
Name: 7, dtype: object
8 -----> StudentID                   PH1009
FullName                Omar Faruq
Data Structure Marks          72.0
Algorithm Marks               72.0
Python Marks                  76.0
CompletionStatus         Completed
EnrollmentDate          2024-05-16
Instructor               Mr. David
Location                     Dhaka
Salary                           0
Name: 8, dtype: object
9 -----> StudentID                     PH1010
FullName                Priya Sharma
Data Structure Marks            89.0
Algorithm Marks                 89.0
Python Marks                    88.0
CompletionStatus           Completed
EnrollmentDate            2024-05-20
Instructor                 Ms. Salma
Location                      Sylhet
Salary                             0
Name: 9, dtype: object
10 -----> StudentID                     PH1011
FullName                Rahim Sheikh
Data Structure Marks             NaN
Algorithm Marks                  NaN
Python Marks                    91.0
CompletionStatus         In Progress
EnrollmentDate            2024-06-11
Instructor                 Mr. Karim
Location                      Khulna
Salary                             0
Name: 10, dtype: object
11 -----> StudentID                        PH1012
FullName                Sadia Chowdhury
Data Structure Marks               85.0
Algorithm Marks                    85.0
Python Marks                       87.0
CompletionStatus              Completed
EnrollmentDate               2024-06-14
Instructor                    Ms. Salma
Location                     Chattogram
Salary                                0
Name: 11, dtype: object
12 -----> StudentID                     PH1013
FullName                Tanvir Ahmed
Data Structure Marks            75.0
Algorithm Marks                 75.0
Python Marks                    79.0
CompletionStatus           Completed
EnrollmentDate            2024-07-02
Instructor                 Mr. David
Location                       Dhaka
Salary                             0
Name: 12, dtype: object
13 -----> StudentID                    PH1014
FullName                 Urmi Akter
Data Structure Marks            NaN
Algorithm Marks                 NaN
Python Marks                    NaN
CompletionStatus        Not Started
EnrollmentDate           2024-07-09
Instructor                Ms. Salma
Location                   Rajshahi
Salary                            0
Name: 13, dtype: object
14 -----> StudentID                     PH1015
FullName                Wahiduzzaman
Data Structure Marks            86.0
Algorithm Marks                 86.0
Python Marks                    84.0
CompletionStatus           Completed
EnrollmentDate            2024-08-18
Instructor                 Mr. Karim
Location                       Dhaka
Salary                             0
Name: 14, dtype: object
15 -----> StudentID                     PH1016
FullName                Ziaur Rahman
Data Structure Marks            94.0
Algorithm Marks                 94.0
Python Marks                     NaN
CompletionStatus         In Progress
EnrollmentDate            2024-08-21
Instructor                 Ms. Salma
Location                  Chattogram
Salary                             0
Name: 15, dtype: object
16 -----> StudentID                    PH1017
FullName                Afsana Mimi
Data Structure Marks           90.0
Algorithm Marks                90.0
Python Marks                   93.0
CompletionStatus          Completed
EnrollmentDate           2025-09-01
Instructor                Mr. Karim
Location                      Dhaka
Salary                            0
Name: 16, dtype: object
17 -----> StudentID                    PH1018
FullName                Babul Ahmed
Data Structure Marks           88.0
Algorithm Marks                88.0
Python Marks                   85.0
CompletionStatus          Completed
EnrollmentDate           2025-09-05
Instructor                Ms. Salma
Location                     Sylhet
Salary                            0
Name: 17, dtype: object
18 -----> StudentID                     PH1019
FullName                Faria Rahman
Data Structure Marks             NaN
Algorithm Marks                  NaN
Python Marks                     NaN
CompletionStatus         Not Started
EnrollmentDate            2025-09-15
Instructor                 Mr. David
Location                  Chattogram
Salary                             0
Name: 18, dtype: object
19 -----> StudentID                   PH1020
FullName                Nasir Khan
Data Structure Marks          86.0
Algorithm Marks               86.0
Python Marks                  89.0
CompletionStatus         Completed
EnrollmentDate          2025-10-02
Instructor               Ms. Salma
Location                     Dhaka
Salary                           0
Name: 19, dtype: object

### itertuples()
faster method

In [100]:
for i in df.itertuples():
    print(i)

Pandas(Index=0, StudentID='PH1001', FullName='Alif Rahman', _3=85.0, _4=85.0, _5=88.0, CompletionStatus='Completed', EnrollmentDate='2024-01-15', Instructor='Mr. Karim', Location='Dhaka', Salary=0)
Pandas(Index=1, StudentID='PH1002', FullName='Fatima Akhter', _3=92.0, _4=92.0, _5=nan, CompletionStatus='In Progress', EnrollmentDate='2024-01-20', Instructor='Ms. Salma', Location='Chattogram', Salary=0)
Pandas(Index=2, StudentID='PH1003', FullName='Imran Hossain', _3=88.0, _4=88.0, _5=85.0, CompletionStatus='Completed', EnrollmentDate='2024-02-10', Instructor='Mr. Karim', Location='Dhaka', Salary=0)
Pandas(Index=3, StudentID='PH1004', FullName='Jannatul Ferdous', _3=78.0, _4=78.0, _5=82.0, CompletionStatus='Completed', EnrollmentDate='2024-02-12', Instructor='Ms. Salma', Location='Sylhet', Salary=0)
Pandas(Index=4, StudentID='PH1005', FullName='Kamal Uddin', _3=nan, _4=nan, _5=95.0, CompletionStatus='In Progress', EnrollmentDate='2024-03-05', Instructor='Mr. Karim', Location='Chattogram', Salary=0)
Pandas(Index=5, StudentID='PH1006', FullName='Laila Begum', _3=75.0, _4=75.0, _5=78.0, CompletionStatus='Completed', EnrollmentDate='2024-03-08', Instructor='Ms. Salma', Location='Rajshahi', Salary=0)
Pandas(Index=6, StudentID='PH1007', FullName='Mahmudul Hasan', _3=80.0, _4=80.0, _5=nan, CompletionStatus='In Progress', EnrollmentDate='2024-04-01', Instructor='Mr. Karim', Location='Dhaka', Salary=0)
Pandas(Index=7, StudentID='PH1008', FullName='Nadia Islam', _3=81.0, _4=81.0, _5=85.0, CompletionStatus='Completed', EnrollmentDate='2024-04-22', Instructor='Ms. Salma', Location='Chattogram', Salary=0)
Pandas(Index=8, StudentID='PH1009', FullName='Omar Faruq', _3=72.0, _4=72.0, _5=76.0, CompletionStatus='Completed', EnrollmentDate='2024-05-16', Instructor='Mr. David', Location='Dhaka', Salary=0)
Pandas(Index=9, StudentID='PH1010', FullName='Priya Sharma', _3=89.0, _4=89.0, _5=88.0, CompletionStatus='Completed', EnrollmentDate='2024-05-20', Instructor='Ms. Salma', Location='Sylhet', Salary=0)
Pandas(Index=10, StudentID='PH1011', FullName='Rahim Sheikh', _3=nan, _4=nan, _5=91.0, CompletionStatus='In Progress', EnrollmentDate='2024-06-11', Instructor='Mr. Karim', Location='Khulna', Salary=0)
Pandas(Index=11, StudentID='PH1012', FullName='Sadia Chowdhury', _3=85.0, _4=85.0, _5=87.0, CompletionStatus='Completed', EnrollmentDate='2024-06-14', Instructor='Ms. Salma', Location='Chattogram', Salary=0)
Pandas(Index=12, StudentID='PH1013', FullName='Tanvir Ahmed', _3=75.0, _4=75.0, _5=79.0, CompletionStatus='Completed', EnrollmentDate='2024-07-02', Instructor='Mr. David', Location='Dhaka', Salary=0)
Pandas(Index=13, StudentID='PH1014', FullName='Urmi Akter', _3=nan, _4=nan, _5=nan, CompletionStatus='Not Started', EnrollmentDate='2024-07-09', Instructor='Ms. Salma', Location='Rajshahi', Salary=0)
Pandas(Index=14, StudentID='PH1015', FullName='Wahiduzzaman', _3=86.0, _4=86.0, _5=84.0, CompletionStatus='Completed', EnrollmentDate='2024-08-18', Instructor='Mr. Karim', Location='Dhaka', Salary=0)
Pandas(Index=15, StudentID='PH1016', FullName='Ziaur Rahman', _3=94.0, _4=94.0, _5=nan, CompletionStatus='In Progress', EnrollmentDate='2024-08-21', Instructor='Ms. Salma', Location='Chattogram', Salary=0)
Pandas(Index=16, StudentID='PH1017', FullName='Afsana Mimi', _3=90.0, _4=90.0, _5=93.0, CompletionStatus='Completed', EnrollmentDate='2025-09-01', Instructor='Mr. Karim', Location='Dhaka', Salary=0)
Pandas(Index=17, StudentID='PH1018', FullName='Babul Ahmed', _3=88.0, _4=88.0, _5=85.0, CompletionStatus='Completed', EnrollmentDate='2025-09-05', Instructor='Ms. Salma', Location='Sylhet', Salary=0)
Pandas(Index=18, StudentID='PH1019', FullName='Faria Rahman', _3=nan, _4=nan, _5=nan, CompletionStatus='Not Started', EnrollmentDate='2025-09-15', Instructor='Mr. David', Location='Chattogram', Salary=0)
Pandas(Index=19, StudentID='PH1020', FullName='Nasir Khan', _3=86.0, _4=86.0, _5=89.0, CompletionStatus='Completed', EnrollmentDate='2025-10-02', Instructor='Ms. Salma', Location='Dhaka', Salary=0)

In [101]:
for i in df.itertuples(index=False):
    print(i)

Pandas(StudentID='PH1001', FullName='Alif Rahman', _2=85.0, _3=85.0, _4=88.0, CompletionStatus='Completed', EnrollmentDate='2024-01-15', Instructor='Mr. Karim', Location='Dhaka', Salary=0)
Pandas(StudentID='PH1002', FullName='Fatima Akhter', _2=92.0, _3=92.0, _4=nan, CompletionStatus='In Progress', EnrollmentDate='2024-01-20', Instructor='Ms. Salma', Location='Chattogram', Salary=0)
Pandas(StudentID='PH1003', FullName='Imran Hossain', _2=88.0, _3=88.0, _4=85.0, CompletionStatus='Completed', EnrollmentDate='2024-02-10', Instructor='Mr. Karim', Location='Dhaka', Salary=0)
Pandas(StudentID='PH1004', FullName='Jannatul Ferdous', _2=78.0, _3=78.0, _4=82.0, CompletionStatus='Completed', EnrollmentDate='2024-02-12', Instructor='Ms. Salma', Location='Sylhet', Salary=0)
Pandas(StudentID='PH1005', FullName='Kamal Uddin', _2=nan, _3=nan, _4=95.0, CompletionStatus='In Progress', EnrollmentDate='2024-03-05', Instructor='Mr. Karim', Location='Chattogram', Salary=0)
Pandas(StudentID='PH1006', FullName='Laila Begum', _2=75.0, _3=75.0, _4=78.0, CompletionStatus='Completed', EnrollmentDate='2024-03-08', Instructor='Ms. Salma', Location='Rajshahi', Salary=0)
Pandas(StudentID='PH1007', FullName='Mahmudul Hasan', _2=80.0, _3=80.0, _4=nan, CompletionStatus='In Progress', EnrollmentDate='2024-04-01', Instructor='Mr. Karim', Location='Dhaka', Salary=0)
Pandas(StudentID='PH1008', FullName='Nadia Islam', _2=81.0, _3=81.0, _4=85.0, CompletionStatus='Completed', EnrollmentDate='2024-04-22', Instructor='Ms. Salma', Location='Chattogram', Salary=0)
Pandas(StudentID='PH1009', FullName='Omar Faruq', _2=72.0, _3=72.0, _4=76.0, CompletionStatus='Completed', EnrollmentDate='2024-05-16', Instructor='Mr. David', Location='Dhaka', Salary=0)
Pandas(StudentID='PH1010', FullName='Priya Sharma', _2=89.0, _3=89.0, _4=88.0, CompletionStatus='Completed', EnrollmentDate='2024-05-20', Instructor='Ms. Salma', Location='Sylhet', Salary=0)
Pandas(StudentID='PH1011', FullName='Rahim Sheikh', _2=nan, _3=nan, _4=91.0, CompletionStatus='In Progress', EnrollmentDate='2024-06-11', Instructor='Mr. Karim', Location='Khulna', Salary=0)
Pandas(StudentID='PH1012', FullName='Sadia Chowdhury', _2=85.0, _3=85.0, _4=87.0, CompletionStatus='Completed', EnrollmentDate='2024-06-14', Instructor='Ms. Salma', Location='Chattogram', Salary=0)
Pandas(StudentID='PH1013', FullName='Tanvir Ahmed', _2=75.0, _3=75.0, _4=79.0, CompletionStatus='Completed', EnrollmentDate='2024-07-02', Instructor='Mr. David', Location='Dhaka', Salary=0)
Pandas(StudentID='PH1014', FullName='Urmi Akter', _2=nan, _3=nan, _4=nan, CompletionStatus='Not Started', EnrollmentDate='2024-07-09', Instructor='Ms. Salma', Location='Rajshahi', Salary=0)
Pandas(StudentID='PH1015', FullName='Wahiduzzaman', _2=86.0, _3=86.0, _4=84.0, CompletionStatus='Completed', EnrollmentDate='2024-08-18', Instructor='Mr. Karim', Location='Dhaka', Salary=0)
Pandas(StudentID='PH1016', FullName='Ziaur Rahman', _2=94.0, _3=94.0, _4=nan, CompletionStatus='In Progress', EnrollmentDate='2024-08-21', Instructor='Ms. Salma', Location='Chattogram', Salary=0)
Pandas(StudentID='PH1017', FullName='Afsana Mimi', _2=90.0, _3=90.0, _4=93.0, CompletionStatus='Completed', EnrollmentDate='2025-09-01', Instructor='Mr. Karim', Location='Dhaka', Salary=0)
Pandas(StudentID='PH1018', FullName='Babul Ahmed', _2=88.0, _3=88.0, _4=85.0, CompletionStatus='Completed', EnrollmentDate='2025-09-05', Instructor='Ms. Salma', Location='Sylhet', Salary=0)
Pandas(StudentID='PH1019', FullName='Faria Rahman', _2=nan, _3=nan, _4=nan, CompletionStatus='Not Started', EnrollmentDate='2025-09-15', Instructor='Mr. David', Location='Chattogram', Salary=0)
Pandas(StudentID='PH1020', FullName='Nasir Khan', _2=86.0, _3=86.0, _4=89.0, CompletionStatus='Completed', EnrollmentDate='2025-10-02', Instructor='Ms. Salma', Location='Dhaka', Salary=0)

## Sorting
sort_values()

In [102]:
# sorted values in ascending order
ascdf = df3.sort_values("Data Structure Marks")
ascdf

,Full Name,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor
StudentID,,,,,,,
PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David
PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma
PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David
PH1004,Jannatul Ferdous,78.0,78.0,83.0,Completed,2024-02-12,Ms. Salma
PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim
PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma
PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma
PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim
PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma
PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma
PH1003,Imran Hossain,88.0,88.0,86.0,Completed,2024-02-10,Mr. Karim
PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma
PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim
PH1002,Fatima Akhter,92.0,92.0,91.0,Completed,2024-01-20,Ms. Salma
PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma
PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim
PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim
PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma
PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David

In [103]:
# sorted values in descending order
dscdf = df3.sort_values("Data Structure Marks", ascending=False)
dscdf

,Full Name,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor
StudentID,,,,,,,
PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma
PH1002,Fatima Akhter,92.0,92.0,91.0,Completed,2024-01-20,Ms. Salma
PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim
PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma
PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma
PH1003,Imran Hossain,88.0,88.0,86.0,Completed,2024-02-10,Mr. Karim
PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim
PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma
PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma
PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma
PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim
PH1004,Jannatul Ferdous,78.0,78.0,83.0,Completed,2024-02-12,Ms. Salma
PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma
PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David
PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David
PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim
PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim
PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma
PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David

In [104]:
# firstly, the data frame will get sorted upon data structure marks, 
# but for any rows if the data structure marks happens to be the same, then
# it will get sorted upon algorithm marks
orderdf = df3.sort_values(["Data Structure Marks", "Algorithm Marks"], ascending=False)
orderdf

,Full Name,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor
StudentID,,,,,,,
PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma
PH1002,Fatima Akhter,92.0,92.0,91.0,Completed,2024-01-20,Ms. Salma
PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim
PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma
PH1003,Imran Hossain,88.0,88.0,86.0,Completed,2024-02-10,Mr. Karim
PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma
PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim
PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma
PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma
PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma
PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim
PH1004,Jannatul Ferdous,78.0,78.0,83.0,Completed,2024-02-12,Ms. Salma
PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma
PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David
PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David
PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim
PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim
PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma
PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David

In [105]:
# firstly, the data frame will get sorted upon data structure marks in descending order, 
# but for any rows if the data structure marks happens to be the same, then
# it will get sorted in ascending order upon algorithm marks
orderdf = df3.sort_values(["Data Structure Marks", "Algorithm Marks"], ascending=[0, 1])
orderdf

,Full Name,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor
StudentID,,,,,,,
PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma
PH1002,Fatima Akhter,92.0,92.0,91.0,Completed,2024-01-20,Ms. Salma
PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim
PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma
PH1003,Imran Hossain,88.0,88.0,86.0,Completed,2024-02-10,Mr. Karim
PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma
PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim
PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma
PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma
PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma
PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim
PH1004,Jannatul Ferdous,78.0,78.0,83.0,Completed,2024-02-12,Ms. Salma
PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma
PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David
PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David
PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim
PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim
PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma
PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David

## incrementing a column by n

In [108]:
df["Python Marks"] += 1

In [109]:
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Salary
0,PH1001,Alif Rahman,85.0,85.0,90.0,Completed,2024-01-15,Mr. Karim,Dhaka,0
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,0
2,PH1003,Imran Hossain,88.0,88.0,87.0,Completed,2024-02-10,Mr. Karim,Dhaka,0
3,PH1004,Jannatul Ferdous,78.0,78.0,84.0,Completed,2024-02-12,Ms. Salma,Sylhet,0
4,PH1005,Kamal Uddin,NaN,NaN,97.0,In Progress,2024-03-05,Mr. Karim,Chattogram,0
5,PH1006,Laila Begum,75.0,75.0,80.0,Completed,2024-03-08,Ms. Salma,Rajshahi,0
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka,0
7,PH1008,Nadia Islam,81.0,81.0,87.0,Completed,2024-04-22,Ms. Salma,Chattogram,0
8,PH1009,Omar Faruq,72.0,72.0,78.0,Completed,2024-05-16,Mr. David,Dhaka,0
9,PH1010,Priya Sharma,89.0,89.0,90.0,Completed,2024-05-20,Ms. Salma,Sylhet,0
10,PH1011,Rahim Sheikh,NaN,NaN,93.0,In Progress,2024-06-11,Mr. Karim,Khulna,0
11,PH1012,Sadia Chowdhury,85.0,85.0,89.0,Completed,2024-06-14,Ms. Salma,Chattogram,0
12,PH1013,Tanvir Ahmed,75.0,75.0,81.0,Completed,2024-07-02,Mr. David,Dhaka,0
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi,0
14,PH1015,Wahiduzzaman,86.0,86.0,86.0,Completed,2024-08-18,Mr. Karim,Dhaka,0
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram,0
16,PH1017,Afsana Mimi,90.0,90.0,95.0,Completed,2025-09-01,Mr. Karim,Dhaka,0
17,PH1018,Babul Ahmed,88.0,88.0,87.0,Completed,2025-09-05,Ms. Salma,Sylhet,0
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram,0
19,PH1020,Nasir Khan,86.0,86.0,91.0,Completed,2025-10-02,Ms. Salma,Dhaka,0

## null values
isnull()

In [123]:
df.isnull()    # True indicates the data to be null

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,True,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,True,True,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False
6,False,False,False,False,True,False,False,False,False
7,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False
10,False,False,True,True,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False
13,False,False,True,True,True,False,False,False,False
14,False,False,False,False,False,False,False,False,False
15,False,False,False,False,True,False,False,False,False
16,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False
18,False,False,True,True,True,False,False,False,False
19,False,False,False,False,False,False,False,False,False

In [126]:
df.isnull().sum()    # counts the number of null values present within each column

StudentID               0
FullName                0
Data Structure Marks    4
Algorithm Marks         4
Python Marks            5
CompletionStatus        0
EnrollmentDate          0
Instructor              0
Location                0
dtype: int64

### filling up the null values with a number

In [125]:
df.fillna(0)    # the null values are replaced with zero

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,0.0,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,0.0,0.0,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,0.0,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,0.0,0.0,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,0.0,0.0,0.0,Not Started,2024-07-09,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,0.0,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,0.0,0.0,0.0,Not Started,2025-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

In [135]:
df["Python_Marks_not_null"] = df["Python Marks"].fillna(df["Python Marks"].mean())
# mean value is getting placed instead of null

In [136]:
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Python_Marks_not_null
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,88.000000
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,85.666667
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,85.000000
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,82.000000
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,95.000000
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,78.000000
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka,85.666667
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,85.000000
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,76.000000
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,88.000000
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,91.000000
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,87.000000
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,79.000000
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi,85.666667
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,84.000000
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram,85.666667
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,93.000000
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,85.000000
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram,85.666667
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,89.000000

## apply()

In [137]:
df["Python Marks doubled"] = df["Python Marks"].apply(lambda x : x ** 2) 
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Python_Marks_not_null,Python Marks doubled
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,88.000000,7744.0
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,85.666667,NaN
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,85.000000,7225.0
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,82.000000,6724.0
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,95.000000,9025.0
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,78.000000,6084.0
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka,85.666667,NaN
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,85.000000,7225.0
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,76.000000,5776.0
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,88.000000,7744.0
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,91.000000,8281.0
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,87.000000,7569.0
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,79.000000,6241.0
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi,85.666667,NaN
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,84.000000,7056.0
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram,85.666667,NaN
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,93.000000,8649.0
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,85.000000,7225.0
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram,85.666667,NaN
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,89.000000,7921.0

In [138]:
df[df["Instructor"] == "Mr. Karim"]

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Python_Marks_not_null,Python Marks doubled
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,88.000000,7744.0
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,85.000000,7225.0
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,95.000000,9025.0
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka,85.666667,NaN
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,91.000000,8281.0
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,84.000000,7056.0
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,93.000000,8649.0

In [143]:
df[(df["Instructor"] == "Mr. Karim") & (df["CompletionStatus"] == "Completed")]

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Python_Marks_not_null,Python Marks doubled
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,88.0,7744.0
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,85.0,7225.0
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,84.0,7056.0
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,93.0,8649.0

In [145]:
df[~(df["Location"] == "Dhaka")]

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Python_Marks_not_null,Python Marks doubled
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,85.666667,NaN
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,82.000000,6724.0
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,95.000000,9025.0
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,78.000000,6084.0
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,85.000000,7225.0
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,88.000000,7744.0
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,91.000000,8281.0
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,87.000000,7569.0
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi,85.666667,NaN
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram,85.666667,NaN
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,85.000000,7225.0
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram,85.666667,NaN

## Finding unique values from a series (column)
unique()

In [148]:
instructors = df["Instructor"].unique()
print(instructors, type(instructors), instructors.dtype)

['Mr. Karim' 'Ms. Salma' 'Mr. David'] <class 'numpy.ndarray'> object

## only showing unique values in data frame

In [269]:
df.drop_duplicates(subset=["Instructor", "Location"], inplace=True)    
# rows having duplicate values of Marks are not being showed
# only shows the first occurance
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Python_Marks_not_null,Python Marks doubled
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,88.000000,7744.0
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,85.666667,NaN
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,82.000000,6724.0
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,95.000000,9025.0
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,78.000000,6084.0
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,76.000000,5776.0
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,91.000000,8281.0
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,89.000000,7921.0